### ISSUE TITLE
node-ytsr deprecated and broken for certain inputs

### ISSUE THREAD

**Issue by WaverlyCole** [codetheweb/muse#1000]
/home/container/node_modules/ytsr/lib/parseItem.js:415
    rawItems = (obj.content.verticalListRenderer || obj.content.horizontalMovieListRenderer).items;
                                                                                             ^
TypeError: Cannot read properties of undefined (reading 'items')
    at parseShelf (/home/container/node_modules/ytsr/lib/parseItem.js:415:94)
    at parseItem (/home/container/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/home/container/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/container/node_modules/ytsr/lib/parseItem.js:119:46)
    at <anonymous> (/home/container/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/home/container/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KeyValueCacheProvider.wrap (/home/container/src/services/key-value-cache.ts:53:20)
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'items')
pls post the the files in /home/container/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.20.2, ytsr: 3.8.4
********************************************************************************************************************************************************************************************************\
/home/container/node_modules/ytsr/lib/parseItem.js:415
    rawItems = (obj.content.verticalListRenderer || obj.content.horizontalMovieListRenderer).items;
                                                                                             ^
TypeError: Cannot read properties of undefined (reading 'items')
    at parseShelf (/home/container/node_modules/ytsr/lib/parseItem.js:415:94)
    at parseItem (/home/container/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/home/container/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/container/node_modules/ytsr/lib/parseItem.js:119:46)
    at <anonymous> (/home/container/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/home/container/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KeyValueCacheProvider.wrap (/home/container/src/services/key-value-cache.ts:53:20)
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'items')
pls post the the files in /home/container/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.20.2, ytsr: 3.8.4
********************************************************************************************************************************************************************************************************\

**Comment by codetheweb** [comment]
Apparently [the module throwing this error is now deprecated](https://github.com/TimeForANinja/node-ytsr), happy to accept a PR replacing this. Otherwise I may be able to get to it this weekend.

**Comment by codetheweb** [comment]
It does seem to still work for most tracks.

**Comment by Kinuseka** [comment]
[Distube's fork of `ytsr`](https://github.com/distubejs/ytsr) seems to work fine. Its being actively maintained until now and I mostly use their fork now instead.

**Comment by C0ntroller** [comment]
> Apparently [the module throwing this error is now deprecated](https://github.com/TimeForANinja/node-ytsr), happy to accept a PR replacing this. Otherwise I may be able to get to it this weekend.

What's the status on this? I set up the bot yesterday and it crashes after a single song every time.
Would it be possible to just srop in a [fork like the one from distube](https://github.com/distubejs/ytsr)?

(Would try and PR myself but I currently have no time :/)

**Comment by xxtensazenxx** [comment]
It worked for me for months and now its broken, with this exact same error
