### ISSUE TITLE
Ive updated the bot to most recent and it now caused issues of not wanting to play and when i request a song it dont play

### ISSUE THREAD

**Issue by CloudGenYT** [codetheweb/muse#1008]
🚫 ope: Error: Cannot find module '/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.31/opus.node'
Require stack:
/home/container/node_modules/@discordjs/opus/lib/index.js
/home/container/node_modules/prism-media/src/util/loader.js
/home/container/node_modules/prism-media/src/opus/Opus.js
/home/container/node_modules/prism-media/src/opus/index.js
/home/container/node_modules/prism-media/src/index.js
Error: Cannot find module 'node-opus'
Require stack:
/home/container/node_modules/prism-media/src/util/loader.js
/home/container/node_modules/prism-media/src/opus/Opus.js
/home/container/node_modules/prism-media/src/opus/index.js
/home/container/node_modules/prism-media/src/index.js
Error: Cannot find module 'opusscript'
Require stack:
/home/container/node_modules/prism-media/src/util/loader.js
/home/container/node_modules/prism-media/src/opus/Opus.js
/home/container/node_modules/prism-media/src/opus/index.js
/home/container/node_modules/prism-media/src/index.js

**Comment by codetheweb** [comment]
Sounds like you probably need to run `yarn install`.

**Comment by CloudGenYT** [comment]
I'm running on bisect hosting idk how to run yarn install on there

**Comment by CloudGenYT** [comment]
TypeError: Cannot read properties of undefined (reading 'items')
    at parseShelf (/home/container/node_modules/ytsr/lib/parseItem.js:415:94)
    at parseItem (/home/container/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/home/container/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/container/node_modules/ytsr/lib/parseItem.js:119:46)
    at <anonymous> (/home/container/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/home/container/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KeyValueCacheProvider.wrap (/home/container/src/services/key-value-cache.ts:53:20)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'items')
pls post the the files in /home/container/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.20.2, ytsr: 3.8.4
********************************************************************************************************************************************************************************************************\

now it giving me this error
