### ISSUE TITLE
[SponsorBlock] Not Found 

### ISSUE THREAD

**Issue by Bennylavaa** [codetheweb/muse#1028]
**What's happening?**
Concisely describe what's going wrong.

**Logs**

Could not fetch skip segments for "ZCMPXytTD2w" : ResponseError: [SponsorBlock] Not Found
    at Object.statusCheck (/usr/app/node_modules/sponsorblock-api/lib/api/utils.js:50:19)
    at SponsorBlock.<anonymous> (/usr/app/node_modules/sponsorblock-api/lib/api/impl/user.js:40:21)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/app/node_modules/sponsorblock-api/lib/api/impl/user.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}

```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
song stops when it hits the ad portion.

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.8.1 from https://hub.docker.com/r/codetheweb/muse
- Docker (if applicable): Portainer
- OS: Debian

**Comment by Bennylavaa** [comment]
P.S. happens with this link https://www.youtube.com/watch?v=ZCMPXytTD2w I assume it happens for anything non music related. Maybe that is intended.

**Comment by codetheweb** [comment]
cc @Charlignon

**Comment by ChifuyuSenpai** [comment]
Hey, 

Getting this issue on v2.8.1.

Any workflow ?
