### ISSUE TITLE
Getting error "Could not parse decipher function" whenever I play anything.

### ISSUE THREAD

**Issue by gabriel-eladi** [codetheweb/muse#1035]
**What's happening?**
I've been using Muse for a few months now, it was working perfectly. Starting today, I began getting an error `🚫 ope: Could not parse decipher function: Error: Could not match ;([A-Za-z0-9_$]{2,}).\w+(` whenever I try to play a song (through a Spotify link, a YouTube link, a YouTube search, none work).

**Logs**
*(I only censored my guild ID)*

```
muse-bot    | 2024-06-03T22:17:42.784Z prisma:client  Prisma Client call:
muse-bot    | 2024-06-03T22:17:42.784Z prisma:client  prisma.setting.findUnique({
muse-bot    |   where: {
muse-bot    |     guildId: 'my-guild-id'
muse-bot    |   }
muse-bot    | })
muse-bot    | 2024-06-03T22:17:42.784Z prisma:client  Generated request:
muse-bot    | 2024-06-03T22:17:42.785Z prisma:client  query {
muse-bot    |   findUniqueSetting(where: {
muse-bot    |     guildId: "my-guild-id"
muse-bot    |   }) {
muse-bot    |     guildId
muse-bot    |     playlistLimit
muse-bot    |     secondsToWaitAfterQueueEmpties
muse-bot    |     leaveIfNoListeners
muse-bot    |     queueAddResponseEphemeral
muse-bot    |     autoAnnounceNextSong
muse-bot    |     defaultVolume
muse-bot    |     createdAt
muse-bot    |     updatedAt
muse-bot    |   }
muse-bot    | }
muse-bot    | 
muse-bot    | 2024-06-03T22:17:42.785Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
muse-bot    | 2024-06-03T22:17:42.882Z muse [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"983c7119a5eeb225","guild_id":"my-guild-id","endpoint":"frankfurt739.discord.media:443"}}
muse-bot    | 2024-06-03T22:17:44.037Z prisma:client  Prisma Client call:
muse-bot    | 2024-06-03T22:17:44.038Z prisma:client  prisma.setting.findUnique({
muse-bot    |   where: {
muse-bot    |     guildId: 'my-guild-id'
muse-bot    |   }
muse-bot    | })
muse-bot    | 2024-06-03T22:17:44.038Z prisma:client  Generated request:
muse-bot    | 2024-06-03T22:17:44.038Z prisma:client  query {
muse-bot    |   findUniqueSetting(where: {
muse-bot    |     guildId: "my-guild-id"
muse-bot    |   }) {
muse-bot    |     guildId
muse-bot    |     playlistLimit
muse-bot    |     secondsToWaitAfterQueueEmpties
muse-bot    |     leaveIfNoListeners
muse-bot    |     queueAddResponseEphemeral
muse-bot    |     autoAnnounceNextSong
muse-bot    |     defaultVolume
muse-bot    |     createdAt
muse-bot    |     updatedAt
muse-bot    |   }
muse-bot    | }
muse-bot    | 
muse-bot    | 2024-06-03T22:17:44.038Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
muse-bot    | 2024-06-03T22:17:44.039Z muse Error: Could not parse decipher function: Error: Could not match ;([A-Za-z0-9_\$]{2,})\.\w+\(
muse-bot    |     at extractDecipher (/usr/app/node_modules/ytdl-core/lib/sig.js:96:13)
muse-bot    |     at exports.extractFunctions (/usr/app/node_modules/ytdl-core/lib/sig.js:117:3)
muse-bot    |     at /usr/app/node_modules/ytdl-core/lib/sig.js:21:29
muse-bot    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional context**
I have tried downgrading to 2.7.1, but I get the same error. To my inexperienced self, it looks like the issue lies with `ytdl`.

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.8.1
- Docker (if applicable): 26.1.3
- OS: Ubuntu Server 22.04 LTS

**Comment by Nannerz** [comment]
Having the same error

**Comment by valexe24** [comment]
Same here on ytdl@v4.11.4-patch.2

**Comment by pablodz** [comment]
Same here 

```log
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +2s
  muse /usr/app/src/services/youtube-api.ts:98
  muse       throw new Error('No video found.');
  muse             ^
  muse 
  muse Error: No video found.
  muse     at default_1.search (/usr/app/src/services/youtube-api.ts:98:13)
  muse     at AddQueryToQueue.addToQueue (/usr/app/src/services/add-query-to-queue.ts:121:21)
  muse     at default_1.execute (/usr/app/src/commands/play.ts:49:5)
  muse     at Client.<anonymous> (/usr/app/src/bot.ts:79:13) +2s
^C  prisma:client:libraryEngine:exitHooks  exit event received: SIGINT +0ms
```

**Comment by 0xC4DE** [comment]
Issue with me too. Just started with Youtube specifically. Not with spotify.

**Comment by STK0Cervanthes** [comment]
yeap same here too 

Fresh set up done a few hours ago 

joins the VC thinks a lot and then gives that error for both Spotify and Youtube

**Comment by torkd** [comment]
Had the same problem yesterday. Building the docker image from [this PR](https://github.com/codetheweb/muse/pull/1031) which migrates to play-dl mitigates the issue (as in it will reproduce songs from youtube, it will still think a lot).

**Comment by gabriel-eladi** [comment]
suddenly, without changing anything, the bot seems to work for me now. it does think longer than usual though.

**Comment by gabriel-eladi** [comment]
since the issue seems to have fixed itself, i will close it now.
