### ISSUE TITLE
Invalidtoken Discord

### ISSUE THREAD

**Issue by Zakhiel2** [codetheweb/muse#1045]
Invalidtoken even though the token is clearly valid (tried it).
![image](https://github.com/user-attachments/assets/e78124a3-0a5f-4bb6-86d6-ec745aeca1ca)

**Versions**
- Muse: 2.8.1
- Docker (if applicable): 4.31.1 (153621)

**Comment by codetheweb** [comment]
could you please try running with the env var `DEBUG=*` and see if it prints anything useful?

**Comment by onedeyepete** [comment]
im actually getting the same error

**Comment by theMycron** [comment]
Make sure to remove any single-quotes around the keys, I had this problem and I solved it by removing them.

**Comment by NefilimPL** [comment]
Same here invailid token

```
Running version 2.10.0 built on 11/4/2024 (commit 716d6d9f4f2cd1a6872e463e9877203a259478a3)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


✔ Database migrations applied.
⠧ 📡 connecting to Discord.../usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136
    const invalidToken = new DiscordjsError(ErrorCodes.TokenInvalid);
                         ^

Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/usr/app/node_modules/discord.js/src/client/Client.js:226:21)
    at default_1.register (/usr/app/src/bot.ts:166:23)
    at startBot (/usr/app/src/index.ts:21:13)
    at <anonymous> (/usr/app/src/scripts/migrate-and-start.ts:84:3) {
  code: 'TokenInvalid'
}

Node.js v18.20.4
```

this is example command
```
docker run -it -v "C:\Users\BOT\muse":/data -e DISCORD_TOKEN='1234567890TOKEN' -e SPOTIFY_CLIENT_ID='' -e SPOTIFY_CLIENT_SECRET='' -e YOUTUBE_API_KEY='0987654321TOKEN' ghcr.io/museofficial/muse:latest
```
I also tried other configurations and entry methods but none worked.

**Comment by Mubelotix** [comment]
I'm pretty sure you guys are using the wrong token. How many characters do you have in your tokens?

**Comment by Amandakmaid** [comment]
is either you paste ur token wrong or something else have you found the issue yet?

**Comment by 404freedomnotfound** [comment]
> is either you paste ur token wrong or something else have you found the issue yet?

if i remember correctly the amount of issues with muse made it unusable for me. and i already had to use a forked version to get it to work. it being an incorrect token is out of the question. if i am here finding this post and writing about it then i am competent enough to have triple checked to see if the token is actually copied correctly. something else is broken here, i have stopped using this bot and i now just use jockie which people in my server are used to anyway. they always complained that even if muse did work that they didn't want to use a command and preferred .play as prefix so... im sorry i can't help more but just speak my truth in hopes people believe me and can recreate the issue. i was hosting this bot in a docker container on my unraid server
