### ISSUE TITLE
Sometimes some songs are not playing and getting possible memory leak warning

### ISSUE THREAD

**Issue by erdanilevicius** [codetheweb/muse#1058]
**What's happening?**
It might not be bug tied to this repo, but from time to time I'm getting errors for possible memory leaks and some songs just do not launch from youtube link, trying music.youtube link does work sometimes.  

Launching bot with `--no-network-family-autoselection` flag does make this issue show up less, but its still present.  Without it getting this warning and it can later result in crash of the bot itself when launching some songs.

**Screenshots**
![image_2024-08-03_151712432](https://github.com/user-attachments/assets/421811cb-7110-4287-acf0-a66d17d9a3f4)

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.0
- Docker (if applicable):
- OS: Ubuntu 22.04 (Server)
- Node.js: 20.16.0
- ffmpeg: 4.4.2-0ubuntu0.22.04.1

**Comment by Recour** [comment]
Same here. Also, when playing a Spotify playlist, the bot will skip over certain songs and only play a few songs of that playlist (always the same songs). 

I found out by continually doing _/now-playing_ and noticed that even though there's no sound, the currently playing song keeps changing.

**Comment by nicolasbuch** [comment]
I'm seeing the same problem. Often appears when putting a few songs in queue and then skipping one with the `/skip` command. 

@codetheweb is this something you have experienced before?

**Comment by sentientyeet** [comment]
Getting this issue as well, error and problem are the same. Running in docker.

**Comment by scagood** [comment]
Stacktrace (inside docker):
```js
(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stateChange listeners added to [Networking]. Use emitter.setMaxListeners() to increase limit
    at __node_internal_genericNodeError (node:internal/errors:865:15)
    at _addListener (node:events:591:17)
    at Networking.addListener (node:events:609:10)
    at VoiceConnection.<anonymous> (/usr/app/src/services/player.ts:120:22)
    at VoiceConnection.emit (node:events:517:28)
    at VoiceConnection.set state (/usr/app/node_modules/@discordjs/voice/src/VoiceConnection.ts:323:8)
    at VoiceConnection.subscribe (/usr/app/node_modules/@discordjs/voice/src/VoiceConnection.ts:664:8)
    at default.play (/usr/app/src/services/player.ts:240:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at default.forward (/usr/app/src/services/player.ts:290:9)
```

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
