### ISSUE TITLE
Error starting new BOT

### ISSUE THREAD

**Issue by Hawolex** [codetheweb/muse#1104]
**What's happening?**
Copied compose info from repo. "se below". added tokes as showed in the readme.
But the bot shows some type of token error and will not start.

Are my token syntax wrong?
Tried with " , ' and without any thing, just =then token direct. 
All fails with same error.

**Logs and Compose**
<details>
<summary>LOGG OUTPUT</summary>
<br>

```
muse-1  | 2024-09-28T10:25:21.571Z prisma:tryLoadEnv  Environment variables not found at null
muse-1  | 2024-09-28T10:25:21.572Z prisma:tryLoadEnv  Environment variables not found at undefined
muse-1  | 2024-09-28T10:25:21.572Z prisma:tryLoadEnv  No Environment variables loaded
muse-1  | 2024-09-28T10:25:21.938Z prisma:client  checkPlatformCaching:postinstall false
muse-1  | 2024-09-28T10:25:21.938Z prisma:client  checkPlatformCaching:ciName undefined
muse-1  | 2024-09-28T10:25:21.939Z prisma:tryLoadEnv  Environment variables not found at null
muse-1  | 2024-09-28T10:25:21.939Z prisma:tryLoadEnv  Environment variables not found at undefined
muse-1  | 2024-09-28T10:25:21.939Z prisma:tryLoadEnv  No Environment variables loaded
muse-1  | 2024-09-28T10:25:21.939Z prisma:client  dirname /usr/app/node_modules/.prisma/client
muse-1  | 2024-09-28T10:25:21.939Z prisma:client  relativePath ../../..
muse-1  | 2024-09-28T10:25:21.939Z prisma:client  cwd /usr/app
muse-1  | 2024-09-28T10:25:21.939Z prisma:client  protocol graphql
muse-1  | 2024-09-28T10:25:21.939Z prisma:client  clientVersion 4.16.0
muse-1  | 2024-09-28T10:25:21.939Z prisma:client  clientEngineType library
muse-1  | 2024-09-28T10:25:21.940Z prisma:client:libraryEngine  internalSetup
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  checkPlatformCaching:postinstall false
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  checkPlatformCaching:ciName undefined
muse-1  | 2024-09-28T10:25:22.459Z prisma:tryLoadEnv  Environment variables not found at null
muse-1  | 2024-09-28T10:25:22.459Z prisma:tryLoadEnv  Environment variables not found at undefined
muse-1  | 2024-09-28T10:25:22.459Z prisma:tryLoadEnv  No Environment variables loaded
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  dirname /usr/app/node_modules/.prisma/client
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  relativePath ../../..
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  cwd /usr/app
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  protocol graphql
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  clientVersion 4.16.0
muse-1  | 2024-09-28T10:25:22.459Z prisma:client  clientEngineType library
muse-1  | 2024-09-28T10:25:22.460Z prisma:client:libraryEngine  internalSetup
muse-1  | ========================================
muse-1  | ========================================
muse-1  | ================= muse =================
muse-1  | ========================================
muse-1  | =========== Made with 🎶 by ============
muse-1  | ==== https://github.com/codetheweb =====
muse-1  | ========================================
muse-1  | ========================================
muse-1  | 
muse-1  | Running version 2.9.4 built on 8/28/2024 (commit 534d8fafaa7f09f7ba940d044b08e6c48f800c7a)
muse-1  | 
muse-1  | 🔧 Need help? https://github.com/codetheweb/muse/discussions/new
muse-1  | 🐛 Bug? https://github.com/codetheweb/muse/issues/new
muse-1  | ✨ New feature? https://github.com/codetheweb/muse/issues/new
muse-1  | ☕ Discussion? https://github.com/codetheweb/muse/discussions/new
muse-1  | 💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb
muse-1  | 
muse-1  | 
muse-1  | - Applying database migrations...
muse-1  | 2024-09-28T10:25:22.507Z prisma:get-platform  Found distro info:
muse-1  | {
muse-1  |   "targetDistro": "debian",
muse-1  |   "familyDistro": "debian",
muse-1  |   "originalDistro": "debian"
muse-1  | }
muse-1  | 2024-09-28T10:25:22.507Z prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu")
muse-1  | 2024-09-28T10:25:22.508Z prisma:get-platform  Found distro info:
muse-1  | {
muse-1  |   "targetDistro": "debian",
muse-1  |   "familyDistro": "debian",
muse-1  |   "originalDistro": "debian"
muse-1  | }
muse-1  | 2024-09-28T10:25:22.508Z prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu")
muse-1  | 2024-09-28T10:25:22.509Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.1.1
muse-1  | 2024-09-28T10:25:22.509Z prisma:get-platform  The parsed libssl version is: 1.1.x
muse-1  | 2024-09-28T10:25:22.510Z prisma:client:engines:resolveEnginePath  enginePath /usr/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
muse-1  | 2024-09-28T10:25:22.523Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.1.1
muse-1  | 2024-09-28T10:25:22.523Z prisma:get-platform  The parsed libssl version is: 1.1.x
muse-1  | 2024-09-28T10:25:22.523Z prisma:client:engines:resolveEnginePath  enginePath /usr/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
muse-1  | 2024-09-28T10:25:22.524Z prisma:client:libraryEngine  library starting
muse-1  | 2024-09-28T10:25:22.525Z prisma:client:libraryEngine  library started
muse-1  | 2024-09-28T10:25:22.539Z prisma:client  prisma.$queryRaw(SELECT COUNT(id) FROM _prisma_migrations, [])
muse-1  | 2024-09-28T10:25:22.542Z prisma:client  Prisma Client call:
muse-1  | 2024-09-28T10:25:22.544Z prisma:client  prisma.$queryRaw({
muse-1  |   query: 'SELECT COUNT(id) FROM _prisma_migrations',
muse-1  |   parameters: {
muse-1  |     values: '[]',
muse-1  |     __prismaRawParameters__: true
muse-1  |   }
muse-1  | })
muse-1  | 2024-09-28T10:25:22.544Z prisma:client  Generated request:
muse-1  | 2024-09-28T10:25:22.544Z prisma:client  mutation {
muse-1  |   queryRaw(
muse-1  |     query: "SELECT COUNT(id) FROM _prisma_migrations"
muse-1  |     parameters: "[]"
muse-1  |   )
muse-1  | }
muse-1  | 
muse-1  | 2024-09-28T10:25:22.545Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
muse-1  | ✔ Database migrations applied.
muse-1  | 2024-09-28T10:25:23.148Z prisma:client:libraryEngine  library starting
muse-1  | 2024-09-28T10:25:23.149Z prisma:client:libraryEngine  library started
muse-1  | 2024-09-28T10:25:23.156Z prisma:client  Prisma Client call:
muse-1  | 2024-09-28T10:25:23.156Z prisma:client  prisma.fileCache.findMany({
muse-1  |   where: undefined,
muse-1  |   orderBy: {
muse-1  |     createdAt: 'asc'
muse-1  |   },
muse-1  |   take: 50
muse-1  | })
muse-1  | 2024-09-28T10:25:23.156Z prisma:client  Generated request:
muse-1  | 2024-09-28T10:25:23.156Z prisma:client  query {
muse-1  |   findManyFileCache(
muse-1  |     orderBy: [
muse-1  |       {
muse-1  |         createdAt: asc
muse-1  |       }
muse-1  |     ]
muse-1  |     take: 50
muse-1  |   ) {
muse-1  |     hash
muse-1  |     bytes
muse-1  |     accessedAt
muse-1  |     createdAt
muse-1  |     updatedAt
muse-1  |   }
muse-1  | }
muse-1  | 
muse-1  | 2024-09-28T10:25:23.156Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
muse-1  | 2024-09-28T10:25:23.159Z muse Evicting oldest files...
muse-1  | 2024-09-28T10:25:23.160Z prisma:client  Prisma Client call:
muse-1  | 2024-09-28T10:25:23.160Z prisma:client  prisma.fileCache.aggregate({
muse-1  |   select: {
muse-1  |     _sum: {
muse-1  |       select: {
muse-1  |         bytes: true
muse-1  |       }
muse-1  |     }
muse-1  |   }
muse-1  | })
muse-1  | 2024-09-28T10:25:23.160Z prisma:client  Generated request:
muse-1  | 2024-09-28T10:25:23.160Z prisma:client  query {
muse-1  |   aggregateFileCache {
muse-1  |     _sum {
muse-1  |       bytes
muse-1  |     }
muse-1  |   }
muse-1  | }
muse-1  | 
muse-1  | 2024-09-28T10:25:23.160Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
muse-1  | 2024-09-28T10:25:23.182Z superagent POST https://accounts.spotify.com/api/token
muse-1  | 2024-09-28T10:25:23.188Z superagent POST https://accounts.spotify.com/api/token
muse-1  | - 📡 connecting to Discord...
muse-1  | 2024-09-28T10:25:23.193Z muse Provided token: "MTE5NTYzNzAwNzY3MDMxMjk4.Gre8hB.***************************************
muse-1  | 2024-09-28T10:25:23.193Z muse Preparing to connect to the gateway...
muse-1  | 2024-09-28T10:25:23.204Z muse No files needed to be evicted. Total size of the cache is currently 0 bytes, and the cache limit is 2000000000 bytes.
muse-1  | 2024-09-28T10:25:23.274Z superagent POST https://accounts.spotify.com/api/token -> 400
muse-1  | 2024-09-28T10:25:23.279Z superagent POST https://accounts.spotify.com/api/token -> 400
muse-1  | 2024-09-28T10:25:23.414Z muse [WS => Manager] Manager was destroyed. Called by:
muse-1  | Error
muse-1  |     at WebSocketManager.destroy (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:326:54)
muse-1  |     at Client.destroy (/usr/app/node_modules/discord.js/src/client/Client.js:251:13)
muse-1  |     at Client.login (/usr/app/node_modules/discord.js/src/client/Client.js:229:12)
muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
muse-1  |     at default_1.register (/usr/app/src/bot.ts:166:5)
muse-1  |     at startBot (/usr/app/src/index.ts:21:3)
muse-1  |     at <anonymous> (/usr/app/src/scripts/migrate-and-start.ts:84:3)
muse-1  | 2024-09-28T10:25:23.415Z prisma:client:libraryEngine:exitHooks  exit event received: 1
muse-1  | /usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136
muse-1  |     const invalidToken = new DiscordjsError(ErrorCodes.TokenInvalid);
muse-1  |                          ^
muse-1  | 
muse-1  | Error [TokenInvalid]: An invalid token was provided.
muse-1  |     at WebSocketManager.connect (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
muse-1  |     at Client.login (/usr/app/node_modules/discord.js/src/client/Client.js:226:21)
muse-1  |     at default_1.register (/usr/app/src/bot.ts:166:23)
muse-1  |     at startBot (/usr/app/src/index.ts:21:13)
muse-1  |     at <anonymous> (/usr/app/src/scripts/migrate-and-start.ts:84:3) {
muse-1  |   code: 'TokenInvalid'
muse-1  | }
muse-1  | 
muse-1  | Node.js v18.20.4
```
</details>

<details>
<summary>Docker-compose </summary>
<br>

```yaml
services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    restart: always
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN="Removed-Token"
      - YOUTUBE_API_KEY="Removed-Token"
      - SPOTIFY_CLIENT_ID="Removed-Token"
      - SPOTIFY_CLIENT_SECRET="Removed-Token"
      - DEBUG=*
```
</details>

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse:  ghcr.io/museofficial/muse:latest
- Docker (if applicable):Docker Engine - Community Version:           27.3.1
- OS: Ubuntu 24.04.1 LTS 
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by 306bobby-android** [comment]
It says your issue. Your discord bot api key is invalid
