### ISSUE TITLE
Bot gets stuck if video is not available

### ISSUE THREAD

**Issue by Hellysonrp** [codetheweb/muse#324]
If you have a playlist with an unavailable video, an unhandled promise rejection occurs and the bot gets stuck. If the music is skipped, everything goes back to normal.

Here is an example:
![Screenshot_11](https://user-images.githubusercontent.com/5438762/133340862-c3ad2fb0-fa8f-4420-8011-f3431dcc32dd.png)

After the current music ends, this happens:

![Screenshot_12](https://user-images.githubusercontent.com/5438762/133340864-a9ad498a-7e0d-46dd-98f7-18a027c05fd6.png)

I'm using the docker version, got it yesterday (d5bc0089b5bc).
This is what is in the console:
```
# docker-compose up
Starting muse_muse_1 ... done
Attaching to muse_muse_1
muse_1  | yarn run v1.22.5
muse_1  | $ node dist/index.js
muse_1  | Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=383336399572828172&scope=bot&permissions=36760640
muse_1  | WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
muse_1  | Error: Output stream closed
muse_1  |     at Timeout._onTimeout (/usr/app/node_modules/fluent-ffmpeg/lib/processor.js:491:25)
muse_1  |     at listOnTimeout (internal/timers.js:557:17)
muse_1  |     at processTimers (internal/timers.js:500:7)
muse_1  | Error: Output stream closed
muse_1  |     at Timeout._onTimeout (/usr/app/node_modules/fluent-ffmpeg/lib/processor.js:491:25)
muse_1  |     at listOnTimeout (internal/timers.js:557:17)
muse_1  |     at processTimers (internal/timers.js:500:7)
muse_1  | (node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
muse_1  | (Use `node --trace-warnings ...` to show where the warning was created)
muse_1  | (node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit
muse_1  | Error: Output stream closed
muse_1  |     at Timeout._onTimeout (/usr/app/node_modules/fluent-ffmpeg/lib/processor.js:491:25)
muse_1  |     at listOnTimeout (internal/timers.js:557:17)
muse_1  |     at processTimers (internal/timers.js:500:7)
muse_1  | (node:27) UnhandledPromiseRejectionWarning: Error: Status code: 410
muse_1  |     at ClientRequest.<anonymous> (/usr/app/node_modules/miniget/dist/index.js:210:27)
muse_1  |     at Object.onceWrapper (events.js:520:26)
muse_1  |     at ClientRequest.emit (events.js:400:28)
muse_1  |     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
muse_1  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
muse_1  |     at TLSSocket.socketOnData (_http_client.js:515:22)
muse_1  |     at TLSSocket.emit (events.js:400:28)
muse_1  |     at addChunk (internal/streams/readable.js:290:12)
muse_1  |     at readableAddChunk (internal/streams/readable.js:265:9)
muse_1  |     at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
muse_1  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
muse_1  | (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
muse_1  | (node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
muse_1  | Error: Output stream closed
muse_1  |     at Timeout._onTimeout (/usr/app/node_modules/fluent-ffmpeg/lib/processor.js:491:25)
muse_1  |     at listOnTimeout (internal/timers.js:557:17)
muse_1  |     at processTimers (internal/timers.js:500:7)
muse_1  | (node:27) UnhandledPromiseRejectionWarning: Error: Status code: 410
muse_1  |     at ClientRequest.<anonymous> (/usr/app/node_modules/miniget/dist/index.js:210:27)
muse_1  |     at Object.onceWrapper (events.js:520:26)
muse_1  |     at ClientRequest.emit (events.js:400:28)
muse_1  |     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
muse_1  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
muse_1  |     at TLSSocket.socketOnData (_http_client.js:515:22)
muse_1  |     at TLSSocket.emit (events.js:400:28)
muse_1  |     at addChunk (internal/streams/readable.js:290:12)
muse_1  |     at readableAddChunk (internal/streams/readable.js:265:9)
muse_1  |     at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
muse_1  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
muse_1  | (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

The error happened two times.

Great bot BTW 😄 
Now that Google is killing almost all the other music bots, selfhosting will become more and more common IMHO.

**Comment by udany** [comment]
Not sure it will help, but you should get the newest version anyway because it updates `ytdl-core` and it's highly advisable to keep that updated.

Could you provide the youtube link to the unavailable song? I tried [this one](https://www.youtube.com/watch?v=ADBKdSCbmiM) but it worked fine

**Comment by Hellysonrp** [comment]
> Could you provide the youtube link to the unavailable song? I tried [this one](https://www.youtube.com/watch?v=ADBKdSCbmiM) but it worked fine

Here is the link: https://www.youtube.com/watch?v=h4rZE_J1beA

Apparently, this music is blocked for my country (Brazil) due to copyright claims.

> Not sure it will help, but you should get the newest version anyway because it updates `ytdl-core` and it's highly advisable to keep that updated.

I'll update and test the bot when I have time (probably tomorrow).

**Comment by udany** [comment]
I think I got it working (Brazilian here as well btw :D), but since I'm not confident on the fix, so I'm not gonna open a PR, instead I'll just explain it here and leave it up to @codetheweb 

I edited the player service's implementation of [forward](https://github.com/codetheweb/muse/blob/master/src/services/player.ts#L164) to be:
```diff
  async forward(skip: number): Promise<void> {
    this.manualForward(skip);

    try {
      if (this.getCurrent() && this.status !== STATUS.PAUSED) {
        await this.play();
      } else {
        this.status = STATUS.PAUSED;

        let settings = await Settings.findByPk(this.voiceConnection?.channel.guild.id);

        if (!settings?.stayAfterQueueEnds) {
          this.disconnect();
        }
      }
    } catch (error: unknown) {
      this.queuePosition--;
+      if (this.queuePosition < this.queue.length - 1) {
+        await this.forward(1);
+      } else {
        throw error;
+      }
    }
  }
```

With this it will automatically skip to the next track if there is one, although, before it can be marked as "fixed" I think it should output a message explaining the song couldn't be played, but I'm not sure where that'd be done

**Comment by codetheweb** [comment]
Thanks for the report @Hellysonrp, I'll probably fix it this weekend. Will add a message saying it couldn't be played.

**Comment by codetheweb** [comment]
This should now be fixed, please test it out when you get a chance and see if it's working.

**Comment by Hellysonrp** [comment]
It's working.
Thank you for your time 😄
