### ISSUE TITLE
Spotify API failure

### ISSUE THREAD

**Issue by RedWuff** [codetheweb/muse#338]
Console Log after trying to start with docker

`yarn run v1.22.5
$ node dist/index.js
(node:29) UnhandledPromiseRejectionWarning: WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.
Details: invalid_client Invalid client.
    at _toError (/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:43:12)
    at /usr/app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/usr/app/node_modules/superagent/lib/node/index.js:905:3)
    at /usr/app/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/usr/app/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (events.js:400:28)
    at Unzip.<anonymous> (/usr/app/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode`

I have no clue how the spotify api works but it seemes to be the problem here?

So i just created a new app on the spotify Dashboard and added the ID and secret. tried this multiple times.

**Comment by codetheweb** [comment]
Looks like you're having the same issue as https://github.com/codetheweb/muse/issues/329. Closing this, please follow that for updates.
