### ISSUE TITLE
DiscordAPIError: Invalid Form Body when playing music

### ISSUE THREAD

**Issue by Daenks** [codetheweb/muse#406]
This issue has been ongoing for a week or more and started suddenly. My initial reaction was that discord changed something in the API, but given there has been no other discussion regarding this here mayhap something else is going on.

Process: 
start the bot
play a song
receive error below

```Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=887880895942496276&scope=bot&permissions=36752448
(node:3054) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (/home/daenks/muse/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/daenks/muse/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async Client.<anonymous> (file:///home/daenks/muse/dist/bot.js:86:17)
(node:3054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The same error occurs regardless of audio source.
I build the latest master as of a few minutes ago and the problem persists for me.

**Comment by codetheweb** [comment]
I just merged https://github.com/codetheweb/muse/pull/397 which may fix what you're seeing, could you pull the latest from master and try again?

**Comment by Daenks** [comment]
Yep, that resolves the error! Thanks a ton! I definitely didn't expect a same day answer, let alone a fix :)

👍👍👍👍👍👍👍

**Comment by codetheweb** [comment]
Glad it worked.

Just a coincidence that a multi week PR gets merged the same day you open an issue. 😛
