### ISSUE TITLE
Cannot play any music

### ISSUE THREAD

**Issue by Jaymus3** [codetheweb/muse#528]
Hello!  I tried to set up this bot and am having trouble actually getting it to play music.  I got it running using the node.js method with a fresh bot account, added the appropriate API keys to a .env file and such, but whenever anyone tries to play a song, we get ``Request failed with status code 403``.  Here's the cli output with DEBUG enabled: 
```muse Cache miss: ["o_Rpr-uMg14"] +3ms
  follow-redirects options {
  protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/youtube/v3/videos?expiresIn=3600&id=o_Rpr-uMg14&key=**censored_key**&part=id,+player,+snippet,+contentDetails,+status,+statistics',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'User-Agent': 'axios/0.19.2'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'www.googleapis.com',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: __node_internal_],
      validateHeaderValue: [Function: __node_internal_],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
  muse Error: Request failed with status code 403
  muse     at createError (/home/server/muse/node_modules/axios/lib/core/createError.js:16:15)
  muse     at settle (/home/server/muse/node_modules/axios/lib/core/settle.js:17:12)
  muse     at IncomingMessage.handleStreamEnd (/home/server/muse/node_modules/axios/lib/adapters/http.js:236:11)
  muse     at IncomingMessage.emit (node:events:532:35)
  muse     at endReadableNT (node:internal/streams/readable:1346:12)
  muse     at processTicksAndRejections (node:internal/process/task_queues:83:21) +113ms```

**Comment by codetheweb** [comment]
Please double check that the Google API key is correct and that it has access to YouTube APIs (see the README for details).

**Comment by MRLokop** [comment]
i have same issue

**Comment by Jaymus3** [comment]
Got it to work by using a different Google account.  Closing this issue.
