### ISSUE TITLE
Getting code error

### ISSUE THREAD

**Issue by Khaled1066** [codetheweb/muse#547]
I am trying to run the code for docker :
docker run -it -v "$(pwd)/data":/data -e DISCORD_TOKEN='' -e SPOTIFY_CLIENT_ID='' -e SPOTIFY_CLIENT_SECRET='' -e YOUTUBE_API_KEY='' codetheweb/muse:latest

and i am getting the below

 muse@1.2.0 env:set-database-url
> node dist/scripts/run-with-database-url.js "node" "--experimental-json-modules" "dist/scripts/migrate-and-start.js"

WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.
Details: invalid_client Invalid client.
    at _toError (/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:43:12)
    at /usr/app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/usr/app/node_modules/superagent/lib/node/index.js:905:3)
    at /usr/app/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/usr/app/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (node:events:390:28)
    at Unzip.<anonymous> (/usr/app/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  body: { error: 'invalid_client', error_description: 'Invalid client' },
  headers: {
    date: 'Wed, 09 Mar 2022 21:43:01 GMT',
    'content-type': 'application/json',
    'set-cookie': [
      '__Host-device_id=AQCPePKx0tQn0LgZv8D-5o2toFKQirVvpeBUITJDcKY83QGSgkrbwOAHa_VFF_vZwEvY8C-IZsM-PZUbtf0glPzh0CODxea_05k;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax',
      'sp_tr=false;Version=1;Domain=accounts.spotify.com;Path=/;Secure;SameSite=Lax'
    ],
    'sp-trace-id': '4c52978f40983106',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    'content-encoding': 'gzip',
    vary: 'Accept-Encoding',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 400
}
file:///usr/app/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node --experimental-json-modules dist/scripts/migrate-and-start.js
    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///usr/app/dist/scripts/run-with-database-url.js:5:5 {
  shortMessage: 'Command failed with exit code 1: node --experimental-json-modules dist/scripts/migrate-and-start.js',
  command: 'node --experimental-json-modules dist/scripts/migrate-and-start.js',
  escapedCommand: 'node --experimental-json-modules "dist/scripts/migrate-and-start.js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npm notice
npm notice New minor version of npm available! 8.1.0 -> 8.5.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.3
npm notice Run npm install -g npm@8.5.3 to update!
npm notice
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by codetheweb** [comment]
Based on the log output, it looks like your Discord token is invalid.

**Comment by Khaled1066** [comment]
Hello thank you for the answer!
so I rest the Discord token and past the new one but I still am getting this

![image](https://user-images.githubusercontent.com/26714670/157602236-52cae747-99df-4c47-b8bd-b099930c6961.png)

**Comment by codetheweb** [comment]
Looks like it's Spotify that's erroring now and not Discord, so at least something changed. I'd double check your Spotify values again. Maybe the client ID and client secret are mixed up?

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
