### ISSUE TITLE
Could not find settings for guild

### ISSUE THREAD

**Issue by hubret** [codetheweb/muse#566]
Generally speaking I'm aware of the v1 changes. I've changed the bot permissions to include `bot` and `applications.commands`. I've also kicked and reinvited the bot to my server.

**Logs**

```
> muse@1.6.0 start
> npm run env:set-database-url -- esmo src/scripts/migrate-and-start.ts


> muse@1.6.0 env:set-database-url
> esmo src/scripts/run-with-database-url.ts "esmo" "src/scripts/migrate-and-start.ts"

(node:8325) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8325) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
(node:8359) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8359) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
========================================
========================================
================= muse =================
========================================
=========== Made with � by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 1.6.0 built on unknown date (commit unknown)

� Need help? https://github.com/codetheweb/muse/discussions/new
� Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
� Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


✔ Database migrations applied.
⠴ � updating commands in all guilds...file:///home/hubret/muse/src/utils/update-permissions-for-guild.ts:10
    throw new Error("could not find settings for guild");
          ^

Error: could not find settings for guild
    at updatePermissionsForGuild (file:///home/hubret/muse/src/utils/update-permissions-for-guild.ts:10:11)
    at async Promise.all (index 0)
    at async Client.<anonymous> (file:///home/hubret/muse/src/bot.ts:118:7)
file:///home/hubret/muse/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///home/hubret/muse/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/hubret/muse/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/hubret/muse/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 1.6.0
- OS: Ubuntu 18.04
- Node: 16.14.0

**Comment by codetheweb** [comment]
Hmm, I'm not sure how it got out of sync but that error means that Muse is in a guild that it doesn't have a record for in its local database.

If you don't care about the data in Muse's database, I would recommend to
1. Shut Muse down
2. Delete the database file (`db.sqlite` in the data directory)
3. Kick Muse
4. Start Muse again

If you want to retain the data, you could manually edit `db.sqlite` and insert a new row into the `Setting` table with the correct guild ID.

Again, not sure how it got out of sync--if you can figure out how to reproduce it I'm happy to investigate further.

**Comment by hubret** [comment]
Worked 👍

**Comment by hubret** [comment]
Oh, also-- my old install of muse was a fork (which was heavily modified)
