### ISSUE TITLE
ffmpeg seems to have options in the wrong order

### ISSUE THREAD

**Issue by hubret** [codetheweb/muse#567]
**Logs**

```
Error: ffmpeg exited with code 1: Option to (record or transcode stop time) cannot be applied to input url https://rr2---sn-2ipaatpm-2iae.googlevideo.com/videoplayback?expire=1647243112&ei=CJsuYtD4F5yz8wSWkJ-ABw&ip=45.56.98.89&id=o-AEmB3OFVW2X1KLQTGick1YaSe6fExYMhQVEf79LMUNLB&itag=251&source=youtube&requiressl=yes&mh=XZ&mm=31%2C29&mn=sn-2ipaatpm-2iae%2Csn-ab5szn7r&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=81250&vprv=1&mime=audio%2Fwebm&ns=WuQQsFVifVOGAJTAw4_ox2sG&gir=yes&clen=4075475&dur=220.321&lmt=1628075317108564&mt=1647221104&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5511222&n=PGa8gUiD4Nwo7w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANOfXA4lwu5TOoFtnn_HR4W8yr5zzXzq-Nl9C0PrXmiIAiAm12lh0iV2e3uNckvTMhUH4VmMhVTpR5oUtOwBhNXC3Q%3D%3D&sig=AOq0QJ8wRQIgfQwkrSUgkOXuH8XznI4wU34K3atxnxNesoldXuSdhFsCIQCAGXNl4T_0_NBniM-IGiFl1P_d3yMVC_11M1paKbTlHQ%3D%3D -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file https://rr2---sn-2ipaatpm-2iae.googlevideo.com/videoplayback?expire=1647243112&ei=CJsuYtD4F5yz8wSWkJ-ABw&ip=45.56.98.89&id=o-AEmB3OFVW2X1KLQTGick1YaSe6fExYMhQVEf79LMUNLB&itag=251&source=youtube&requiressl=yes&mh=XZ&mm=31%2C29&mn=sn-2ipaatpm-2iae%2Csn-ab5szn7r&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=81250&vprv=1&mime=audio%2Fwebm&ns=WuQQsFVifVOGAJTAw4_ox2sG&gir=yes&clen=4075475&dur=220.321&lmt=1628075317108564&mt=1647221104&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5511222&n=PGa8gUiD4Nwo7w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANOfXA4lwu5TOoFtnn_HR4W8yr5zzXzq-Nl9C0PrXmiIAiAm12lh0iV2e3uNckvTMhUH4VmMhVTpR5oUtOwBhNXC3Q%3D%3D&sig=AOq0QJ8wRQIgfQwkrSUgkOXuH8XznI4wU34K3atxnxNesoldXuSdhFsCIQCAGXNl4T_0_NBniM-IGiFl1P_d3yMVC_11M1paKbTlHQ%3D%3D.
Error opening input files: Invalid argument

    at ChildProcess.<anonymous> (/home/hubret/muse/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 1.6.0
- OS: ubuntu 18

**Comment by bokherus** [comment]
Not sure if it's related to my refactoring https://github.com/codetheweb/muse/pull/550/files#diff-56fde53d4e5107906947fc7476ccd5da900c3a183a34c8137a17080f55416669R459

Could you please try checking out to tag v1.3.0 and see if you can reproduce this?

**Comment by hubret** [comment]
i've been having even stranger issues <1.6.0. This is the only output for 1.3.0:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/hubret/muse/dist/scripts/run-with-database-url.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by hubret** [comment]
Sorry! forgot to kick the bot and reinvite. anyway, the ffmpeg issue still exists in 1.3.0 @bokherus :

```
> muse@1.3.0 start
> npm run env:set-database-url -- node --experimental-json-modules dist/scripts/migrate-and-start.js


> muse@1.3.0 env:set-database-url
> node dist/scripts/run-with-database-url.js "node" "--experimental-json-modules" "dist/scripts/migrate-and-start.js"

========================================
========================================
================= muse =================
========================================
=========== Made with � by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 1.3.0 built on unknown date (commit unknown)

� Need help? https://github.com/codetheweb/muse/discussions/new
� Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
� Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


✔ Database migrations applied.
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=880519287553536041&scope=bot%20applications.commands&permissions=36700160
Error: ffmpeg exited with code 1: Option to (record or transcode stop time) cannot be applied to input url https://rr2---sn-2ipaatpm-2iae.googlevideo.com/videoplayback?expire=1647288715&ei=K00vYtu-AseEhwbmtaHYAQ&ip=45.56.98.89&id=o-AA2VV-dFh1tlY_Yzm6eex35CBMwDVuRD6ER8IVDRcS09&itag=251&source=youtube&requiressl=yes&mh=XZ&mm=31%2C29&mn=sn-2ipaatpm-2iae%2Csn-ab5szn7r&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=173750&vprv=1&mime=audio%2Fwebm&ns=MZI-HSmixeORHPw6ZRX1Cl4G&gir=yes&clen=4075475&dur=220.321&lmt=1628075317108564&mt=1647266704&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5511222&n=nPqdiSe_T1WKWQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANS9nUd-H2DBlQwU3fumRuC7g9zsSHTk0xrg7WAEGhBXAiEAjyz5A2vRYZvvtfzP0CYahmmd6hGqgn33YJPfjl_rZfI%3D&sig=AOq0QJ8wRQIhAJM__f_j4wNUiZ-biVwMZyfPJd5DYVMkFNepafaAL7hwAiAbRmPSWMufokLjyo0NibPXedwEI3Z5CZjtoWVnhJwRRg%3D%3D -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file https://rr2---sn-2ipaatpm-2iae.googlevideo.com/videoplayback?expire=1647288715&ei=K00vYtu-AseEhwbmtaHYAQ&ip=45.56.98.89&id=o-AA2VV-dFh1tlY_Yzm6eex35CBMwDVuRD6ER8IVDRcS09&itag=251&source=youtube&requiressl=yes&mh=XZ&mm=31%2C29&mn=sn-2ipaatpm-2iae%2Csn-ab5szn7r&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=173750&vprv=1&mime=audio%2Fwebm&ns=MZI-HSmixeORHPw6ZRX1Cl4G&gir=yes&clen=4075475&dur=220.321&lmt=1628075317108564&mt=1647266704&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5511222&n=nPqdiSe_T1WKWQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANS9nUd-H2DBlQwU3fumRuC7g9zsSHTk0xrg7WAEGhBXAiEAjyz5A2vRYZvvtfzP0CYahmmd6hGqgn33YJPfjl_rZfI%3D&sig=AOq0QJ8wRQIhAJM__f_j4wNUiZ-biVwMZyfPJd5DYVMkFNepafaAL7hwAiAbRmPSWMufokLjyo0NibPXedwEI3Z5CZjtoWVnhJwRRg%3D%3D.
Error opening input files: Invalid argument

    at ChildProcess.<anonymous> (/home/hubret/muse/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by hubret** [comment]
Multiple different queries had the same outcome. But it turns out its a ffmpeg version issue:

I just tried muse v1.6.0 on a fresh install of Ubuntu 20/Node 16, and it works without a hitch.
v1.6.0 on Ubuntu 18/Node 16 doesn't work.

ffmpeg version is 4.2.4 on Ubuntu 20, 3.4.8 on 18 LTS. I read somewhere that ffmpeg after a certain version allowed an option to be passed before the input file. Not sure exactly which version is required for muse to work, but if anyone can figure that out it would be good to put into the muse prerequisites.
