### ISSUE TITLE
WebapiAuthenticationError

### ISSUE THREAD

**Issue by kferrano** [codetheweb/muse#643]
**What's happening?**
WebapiAuthenticationError

**Logs**

```
unning version 1.9.0 built on 4/23/2022 (commit 1ef05aba9d2e692ef365721f725be2d2a4e464d9)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


✔ Database migrations applied.
⠋ 📡 connecting to Discord.../usr/app/node_modules/spotify-web-api-node/src/http-manager.js:43
    return new WebapiAuthenticationError(response.body, response.headers, response.statusCode);
           ^

WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.
Details: invalid_client Invalid client.
    at _toError (/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:43:12)
    at /usr/app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/usr/app/node_modules/superagent/lib/node/index.js:905:3)
    at /usr/app/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/usr/app/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (node:events:390:28)
    at Unzip.<anonymous> (/usr/app/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  body: { error: 'invalid_client', error_description: 'Invalid client' },
  headers: {
    date: 'Sun, 08 May 2022 19:59:18 GMT',
    'content-type': 'application/json',
    'set-cookie': [
      '__Host-device_id=AQAcSbl8pWA8gApbw99U8qDaZa8d8FiXJxdHW6HBGIFHTbgfRGTd9-rYAYuvCuC1f6oMUqD2kS7xFTpkUXfjkUoShkf9Sb6r_BU;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax',
      'sp_tr=false;Version=1;Domain=accounts.spotify.com;Path=/;Secure;SameSite=Lax'
    ],
    'sp-trace-id': 'ae6747f1753a1ec2',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    'content-encoding': 'gzip',
    vary: 'Accept-Encoding',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 400
}
file:///usr/app/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npm notice
npm notice New minor version of npm available! 8.1.0 -> 8.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.9.0
npm notice Run npm install -g npm@8.9.0 to update!
npm notice
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest
- Docker (if applicable):
- OS: Windows Server 2019

**Comment by codetheweb** [comment]
Issue is what it says. Your client ID for Spotify is probably wrong.

With that noted, the bot is currently broken. Please follow https://github.com/codetheweb/muse/pull/640 for updates.

**Comment by kferrano** [comment]
The Client ID is 100% correct.

So the bot is currently useless as it doesn't work right?

**Comment by codetheweb** [comment]
The bot is now working again with https://github.com/codetheweb/muse/releases/tag/v2.0.0.

Please upgrade and let me know if you're still having issues with Spotify.

**Comment by kferrano** [comment]
The bot works.
But when running command to seetup: `npm i` does that come https://prnt.sc/UbVT__Vsm9vr

**Comment by codetheweb** [comment]
Glad it works now; npm is showing warnings in your screenshot but it's not an issue.
