### ISSUE TITLE
Version 2.0.3 will not start due to new Spotify library version(?)

### ISSUE THREAD

**Issue by nullstalgia** [codetheweb/muse#660]
**What's happening?**
When running Muse 2.0.3 on my unRAID server (as a docker container), it fails on startup.

When switching back to 2.0.2, the issue does not appear.

**Logs**

```
yarn run v1.22.15
$ npm run env:set-database-url -- esmo src/scripts/migrate-and-start.ts

> muse@2.0.3 env:set-database-url
> esmo src/scripts/run-with-database-url.ts "esmo" "src/scripts/migrate-and-start.ts"

(node:53) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
(node:94) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:94) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
file:///usr/app/src/services/get-songs.ts:29
import spotifyURI from "spotify-uri";
^^^^^^^^^^
SyntaxError: The requested module 'spotify-uri' does not provide an export named 'default'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
at async loadESM (node:internal/process/esm_loader:88:5)
at async handleMainPromise (node:internal/modules/run_main:65:12)
file:///usr/app/node_modules/execa/lib/error.js:59
error = new Error(message);
^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
command: 'esmo src/scripts/migrate-and-start.ts',
escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
exitCode: 1,
signal: undefined,
signalDescription: undefined,
stdout: undefined,
stderr: undefined,
failed: true,
timedOut: false,
isCanceled: false,
killed: false
}
npm notice
npm notice New minor version of npm available! 8.1.0 -> 8.10.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>
npm notice Run `npm install -g npm@8.10.0` to update!
npm notice
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Screenshots**

v2.0.2
![image](https://user-images.githubusercontent.com/20761757/168518040-51581452-e145-4d01-aaf9-de69d3dd6138.png)

v2.0.3
![image](https://user-images.githubusercontent.com/20761757/168518051-0cb9a071-f1ef-47bd-9bfc-f924ac998951.png)

**Additional context**

**Runtime**
I'm running Muse:
- [x] Without any changes
- [x] Inside a Docker container
- [x] Something else (please elaborate)

**Versions**
- Muse: v2.0.3
- Docker (if applicable): 20.10.5
- OS: unRAID 6.9.2

**Comment by codetheweb** [comment]
My bad, sorry about that.
