### ISSUE TITLE
Perms error disocord api

### ISSUE THREAD

**Issue by joloman2** [codetheweb/muse#677]
**What's happening?**
the bot crashes on start up i have tryed to reinvite the bot did not fix it also remove the data dir to try and fix it did not work 

**Logs**

```
:~/muse$ sudo docker-compose up
Starting muse_muse_1 ... done
Attaching to muse_muse_1
muse_1  | yarn run v1.22.15
muse_1  | $ npm run env:set-database-url -- esmo src/scripts/migrate-and-start.ts
muse_1  |
muse_1  | > muse@1.8.2 env:set-database-url
muse_1  | > esmo src/scripts/run-with-database-url.ts "esmo" "src/scripts/migrate-and-start.ts"
muse_1  |
muse_1  | (node:51) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
muse_1  | (Use `node --trace-warnings ...` to show where the warning was created)
muse_1  | (node:51) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
muse_1  | (node:96) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
muse_1  | (Use `node --trace-warnings ...` to show where the warning was created)
muse_1  | (node:96) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
muse_1  | ========================================
muse_1  | ========================================
muse_1  | ================= muse =================
muse_1  | ========================================
muse_1  | =========== Made with 🎶 by ============
muse_1  | ==== https://github.com/codetheweb =====
muse_1  | ========================================
muse_1  | ========================================
muse_1  |
muse_1  | Running version 1.8.2 built on 3/27/2022 (commit ce017090e1c2db0a214e959e437d29fd8069fd05)
muse_1  |
muse_1  | 🔧 Need help? https://github.com/codetheweb/muse/discussions/new
muse_1  | 🐛 Bug? https://github.com/codetheweb/muse/issues/new
muse_1  | ✨ New feature? https://github.com/codetheweb/muse/issues/new
muse_1  | ☕ Discussion? https://github.com/codetheweb/muse/discussions/new
muse_1  | 💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb
muse_1  |
muse_1  |
muse_1  | - Applying database migrations...
muse_1  | ✔ Database migrations applied.
muse_1  | - 📡 connecting to Discord...
muse_1  | ✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=965166495686615060&scope=bot%20applications.commands&permissions=36700288
muse_1  | /usr/app/node_modules/discord.js/src/rest/RequestHandler.js:350
muse_1  |       throw new DiscordAPIError(data, res.status, request);
muse_1  |             ^
muse_1  |
muse_1  | DiscordAPIError: 405: Method Not Allowed
muse_1  |     at RequestHandler.execute (/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
muse_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
muse_1  |     at async RequestHandler.push (/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
muse_1  |     at async ApplicationCommandPermissionsManager.set (/usr/app/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:186:18)
muse_1  |     at async updatePermissionsForGuild (file:///usr/app/src/utils/update-permissions-for-guild.ts:32:3)
muse_1  |     at async Client.guild_create_default (file:///usr/app/src/events/guild-create.ts:36:3) {
muse_1  |   method: 'put',
muse_1  |   path: '/applications/965166495686615060/guilds/960352345999409212/commands/permissions',
muse_1  |   code: 0,
muse_1  |   httpStatus: 405,
muse_1  |   requestData: {
muse_1  |     json: [
muse_1  |       {
muse_1  |         id: '977321429542522931',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321429542522932',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321429542522933',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321429542522934',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321429542522935',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434590',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434591',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434592',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434593',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434594',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434595',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434596',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434597',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434598',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430058434599',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430373003284',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       },
muse_1  |       {
muse_1  |         id: '977321430373003285',
muse_1  |         permissions: [
muse_1  |           { id: '298896818769625088', permission: true, type: 2 },
muse_1  |           { id: '960352345999409212', permission: false, type: 1 },
muse_1  |           { id: '259330443529289728', permission: true, type: 2 }
muse_1  |         ]
muse_1  |       }
muse_1  |     ],
muse_1  |     files: []
muse_1  |   }
muse_1  | }
muse_1  | file:///usr/app/node_modules/execa/lib/error.js:59
muse_1  |               error = new Error(message);
muse_1  |                       ^
muse_1  |
muse_1  | Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
muse_1  |     at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
muse_1  |     at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
muse_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
muse_1  |     at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
muse_1  |   shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
muse_1  |   command: 'esmo src/scripts/migrate-and-start.ts',
muse_1  |   escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
muse_1  |   exitCode: 1,
muse_1  |   signal: undefined,
muse_1  |   signalDescription: undefined,
muse_1  |   stdout: undefined,
muse_1  |   stderr: undefined,
muse_1  |   failed: true,
muse_1  |   timedOut: false,
muse_1  |   isCanceled: false,
muse_1  |   killed: false
muse_1  | }
muse_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
muse_1  | error Command failed with exit code 1.

```

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/64356554/169615133-fccfa865-110c-43ed-8bf8-bae6f4407f4c.png)

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest 
- Docker (if applicable): composer latest
- OS:Linux ubuntu latest

**Comment by joloman2** [comment]
it seems to be running on version 1.8.2 but idk why its doing that

**Comment by codetheweb** [comment]
Try `docker-compose pull` and then `docker-compose up` again.

**Comment by joloman2** [comment]
thank you that worked you should maybe add that to the readme. so ppl know how to update it
