### ISSUE TITLE
  rawError: { message: 'Missing Access', code: 50001 }

### ISSUE THREAD

**Issue by gamer228** [codetheweb/muse#681]
Hello, 

I'm having some problems getting the bot to work, here's the output with the error.  I hope someone can help me out?

```
✔ Database migrations applied.
⠹ 📡 updating commands in all guilds...DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:670:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:473:14)
    at async registerCommandsOnGuild (file:///usr/app/src/utils/register-commands-on-guild.ts:3:3)
    at async file:///usr/app/src/bot.ts:111:13
    at async Promise.all (index 0)
    at async Client.<anonymous> (file:///usr/app/src/bot.ts:109:9) {
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v10/applications/979141860264120391/guilds/241131244216123392/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ]
  }
}
⠦ 📡 updating commands in all guilds...
```

**Comment by joepboumans** [comment]
I have exactly the same problem, but I do not have a clue how to fix it.

**Comment by codetheweb** [comment]
Issue is what it says, the bot isn't allowed to create slash commands in your guild. Try kicking Muse and make sure you re-invite with the logged invite link.

**Comment by samrudd** [comment]
i have this issue too, bot has full administrator access to the server so im stumped

**Comment by codetheweb** [comment]
V1 changed the permissions since slash commands were introduced. If you've been using Muse for a while you'll have to re-invite.
