### ISSUE TITLE
Bot joins voice chat but is silent  and eventually exits

### ISSUE THREAD

**Issue by unixbird** [codetheweb/muse#687]
**What's happening?**
I attempt to query a song and it joins the voice chat but does not actually play anything.

**Logs**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [ X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest
- Docker (if applicable): 20.10.6
- OS: Ubuntu 22.04

**Comment by unixbird** [comment]
It did not seem to display my logs so here they are


`file:///usr/app/node_modules/@discordjs/voice/dist/index.mjs:309
      this.socket.once("close", () => reject(new Error("Cannot perform IP discovery - socket closed")));
                                             ^
Error: Cannot perform IP discovery - socket closed
    at Socket.<anonymous> (file:///usr/app/node_modules/@discordjs/voice/dist/index.mjs:309:46)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:402:35)
    at socketCloseNT (node:dgram:755:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processTimers (node:internal/timers:497:9)
Emitted 'error' event on VoiceConnection instance at:
    at VoiceConnection2.onNetworkingError (file:///usr/app/node_modules/@discordjs/voice/dist/index.mjs:1487:10)
    at Networking.emit (node:events:390:28)
    at file:///usr/app/node_modules/@discordjs/voice/dist/index.mjs:645:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processTimers (node:internal/timers:497:9)
file:///usr/app/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^
Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npm notice 
npm notice New minor version of npm available! 8.1.0 -> 8.11.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.11.0>
npm notice Run `npm install -g npm@8.11.0` to update!
npm notice 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by codetheweb** [comment]
Haven't seen that error before but it looks like something might be going on with the network layer that's outside of Muse's control. Can you try running from the repository (outside a container) to rule out Docker networking?

**Comment by unixbird** [comment]
> 

I have actually confirmed it's something outside of Muse and Docker. It looks like its complaining about not being able to potentially use upnp with the 4xxxx - 5xxxx range of ports that discord uses for voice connections. The error above was on a Hetzner Dedicated server but when switching back to my own cluster it works perfectly
