### ISSUE TITLE
Muse crashes when message is sent to a voice chat channel

### ISSUE THREAD

**Issue by Kamaroth92** [codetheweb/muse#689]
Discord has added the ability to create chat channels for voice groups. Muse appears to crash if a message is sent to channel it has joined. I am using the latest image that was pushed 18 days ago.

`WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
/usr/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/usr/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/usr/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/usr/app/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/usr/app/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/usr/app/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/usr/app/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/usr/app/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/usr/app/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.socketOnData (/usr/app/node_modules/ws/lib/websocket.js:909:35)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by codetheweb** [comment]
Happy to accept a PR for this. :)
