### ISSUE TITLE
Spotify or Youtube not working.

### ISSUE THREAD

**Issue by MrFoxyOfficial** [codetheweb/muse#715]
**What's happening?**
I'm trying to play the 

**Logs**

For Spotify:
```
 prisma:client Prisma Client call: +19s
  prisma:client prisma.setting.findUnique({
  prisma:client   where: {
  prisma:client     guildId: '925495915857469513'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findUniqueSetting(where: {
  prisma:client     guildId: "925495915857469513"
  prisma:client   }) {
  prisma:client     guildId
  prisma:client     playlistLimit
  prisma:client     secondsToWaitAfterQueueEmpties
  prisma:client     leaveIfNoListeners
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +19s
  superagent GET https://api.spotify.com/v1/albums/7AWypqsu3ELcmgpgpg5eSd +19s
  superagent GET https://api.spotify.com/v1/albums/7AWypqsu3ELcmgpgpg5eSd/tracks?limit=50 +3ms
  superagent GET https://api.spotify.com/v1/albums/7AWypqsu3ELcmgpgpg5eSd/tracks?limit=50 -> 200 +179ms
  superagent GET https://api.spotify.com/v1/albums/7AWypqsu3ELcmgpgpg5eSd -> 200 +11ms
  prisma:client Prisma Client call: +499ms
  prisma:client prisma.keyValueCache.findUnique({
  prisma:client   where: {
  prisma:client     key: '["\"Dragonborn - Original Mix\" \"Headhunterz\"",{"limit":10}]'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findUniqueKeyValueCache(where: {
  prisma:client     key: "[\"\\\"Dragonborn - Original Mix\\\" \\\"Headhunterz\\\"\",{\"limit\":10}]"
  prisma:client   }) {
  prisma:client     key
  prisma:client     value
  prisma:client     expiresAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +501ms
  muse Cache hit: ["\"Dragonborn - Original Mix\" \"Headhunterz\"",{"limit":10}] +18s
  prisma:client Prisma Client call: +6ms
  prisma:client prisma.keyValueCache.findUnique({
  prisma:client   where: {
  prisma:client     key: '["VaiHTvifGt0"]'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +2ms
  prisma:client query {
  prisma:client   findUniqueKeyValueCache(where: {
  prisma:client     key: "[\"VaiHTvifGt0\"]"
  prisma:client   }) {
  prisma:client     key
  prisma:client     value
  prisma:client     expiresAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +7ms
  muse Cache miss: ["VaiHTvifGt0"] +7ms
  follow-redirects options {
      validateHeaderValue: [Function: __node_internal_],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
  muse Error: no songs found
  muse     at AddQueryToQueue.addToQueue (file:///C:/Users/deadg/Desktop/muse-master/src/services/add-query-to-queue.ts:115:13)
  muse     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  muse     at async play_default.execute (file:///C:/Users/deadg/Desktop/muse-master/src/commands/play.ts:29:5)
  muse     at async Client.<anonymous> (file:///C:/Users/deadg/Desktop/muse-master/src/bot.ts:69:13) +182ms
```

For youtube:
I've pasted it into Pastebin, as it was a bit too big xD
https://pastebin.com/SRabttLF

**Screenshots**
Youtube error:
![image](https://user-images.githubusercontent.com/1783339/175916475-d9045a2e-768f-47b4-974c-e70105f745ff.png)

Spotify error:
![image](https://user-images.githubusercontent.com/1783339/175916515-5f8ad4ad-6a31-483c-b99d-3e56041f8490.png)

**Additional context**
I didn't get any error while running `npm i` and also I'm not that skilled in terms of coding.

**Runtime**
I'm running Muse:
- [ X] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.1.0
- Docker (if applicable): N/A
- OS: Windows 11 Home (OS Build: 22000.739)

Any help would be greatly appreciated.

**Comment by AndreasWidmer** [comment]
same here. fresh docker installation

**Comment by codetheweb** [comment]
What's your ffmpeg version?

**Comment by MrFoxyOfficial** [comment]
> What's your ffmpeg version?

```
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```


Moved from windows to my VPS and still, the same error + I'm getting a bunch of errors just by trying to search for music.

**Comment by codetheweb** [comment]
If you're getting a 403 on YouTube I'm guessing the API key you generated isn't working for some reason. Make sure the YouTube API is enabled and the API key has access to it.

**Comment by MrFoxyOfficial** [comment]
Ok, and what about spotify?

**Comment by codetheweb** [comment]
Muse doesn't stream from Spotify, it searches for the same tracks on YouTube if you give it a Spotify source. Let's get it working with YouTube first. :)

**Comment by MrFoxyOfficial** [comment]
Yeah, about that xD hahaha
![image](https://user-images.githubusercontent.com/1783339/176573716-e60f0d4f-b380-4876-be65-fc0a0d9088ac.png)

If it's not playing from Spotify, why do we have to provide API keys then for it?

**Comment by DrowningWhale** [comment]
> 

The Spotify API keys are used to query the song details and search them on YouTube since Spotify doesn't let you stream from it from their platform due to licensing. I believe all music bots do this.
