### ISSUE TITLE
Youtube works, but not Youtube links

### ISSUE THREAD

**Issue by azukaar** [codetheweb/muse#716]
**What's happening?**

if I do /play "query", it works fine, but /play youtube.com/.... will show `Nope: Could not find settings for guild`

**Logs**

```
2022-06-27T16:18:27.211Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 110ms.

✔ Ready! Invite the bot with....

2022-06-27T16:18:36.243Z prisma:client Prisma Client call:
2022-06-27T16:18:36.243Z prisma:client prisma.setting.findUnique({
  where: {
    guildId: '...'
  }
})

2022-06-27T16:18:36.243Z prisma:client Generated request:
2022-06-27T16:18:36.243Z prisma:client query {
  findUniqueSetting(where: {
    guildId: "..."
  }) {
    guildId
    playlistLimit
    secondsToWaitAfterQueueEmpties
    leaveIfNoListeners
    createdAt
    updatedAt
  }
}

2022-06-27T16:18:36.244Z prisma:client:libraryEngine sending request, this.libraryStarted: true
2022-06-27T16:18:36.245Z muse Error: Could not find settings for guild
    at AddQueryToQueue.addToQueue (file:///usr/app/src/services/add-query-to-queue.ts:56:13)
    at async play_default.execute (file:///usr/app/src/commands/play.ts:29:5)
    at async Client.<anonymous> (file:///usr/app/src/bot.ts:69:13)

2022-06-27T16:18:39.925Z agentkeepalive sock[0#registry.yarnpkg.com:443::::::::true:::::::::::::](requests: 1, finished: 1) timeout after 15000ms, listeners 2, defaultTimeoutListenerCount 3, hasHttpRequest false, HttpRequest timeoutListenerCount 0

2022-06-27T16:18:39.925Z agentkeepalive timeout listeners: onTimeout, onTimeout

2022-06-27T16:18:39.926Z agentkeepalive sock[0#registry.yarnpkg.com:443::::::::true:::::::::::::] is free, destroy quietly

2022-06-27T16:18:39.926Z agentkeepalive sock[0#registry.yarnpkg.com:443::::::::true:::::::::::::](requests: 1, finished: 1) close, isError: false
```

**Runtime**
I'm running Muse:
- [ * ] Directly from the cloned repository
- [ * ] Inside a Docker container
- 
**Versions**
- Muse: latest tag
- OS: Linux

**Comment by azukaar** [comment]
Nevermind, the server wasn't persisting sorry

**Comment by azukaar** [comment]
Reopening, as I thought it was gone,  but I think the issue is just intermittent

in this screenshot I typed 
(1) /play https://www.youtube.com/watch?v=0r12JCTpEt0
(2) /play anything

![image](https://user-images.githubusercontent.com/7872597/176409761-92c0baf5-c67b-4ee5-809b-14fe28323b0d.png)

**Comment by codetheweb** [comment]
Try deleting your .sqlite database, kicking Muse, and re-inviting.

**Comment by azukaar** [comment]
I did it, it does work for now!
