### ISSUE TITLE
Crash, log attached

### ISSUE THREAD

**Issue by azukaar** [codetheweb/muse#719]
**What's happening?**
Server crashed, I did not see the crash right away so I am not sure what caused it, but here's the log:

```
2022-07-02T11:04:34.785Z superagent POST https://accounts.spotify.com/api/token -> 200
2022-07-02T11:04:34.819Z superagent POST https://accounts.spotify.com/api/token -> 200
2022-07-02T11:04:35.128Z superagent POST https://accounts.spotify.com/api/token
2022-07-02T11:04:35.171Z superagent POST https://accounts.spotify.com/api/token -> 503
2022-07-02T11:04:35.176Z prisma:client:libraryEngine hookProcess received: exit
2022-07-02T11:04:35.176Z prisma:client:libraryEngine runBeforeExit
/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:47
  return new WebapiError(response.body, response.headers, response.statusCode, response.body);
         ^
        WebapiError: [object Object]
    at _toError (/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:47:10)

    at /usr/app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/usr/app/node_modules/superagent/lib/node/index.js:905:3)
    at IncomingMessage.<anonymous> (/usr/app/node_modules/superagent/lib/node/index.js:1127:20)
    at Stream.emit (node:events:390:28)
    at Unzip.<anonymous> (/usr/app/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  body: {},
```

**Runtime**
I'm running Muse:
- [*] Inside a Docker container

**Versions**
- Muse: latest
- OS: linux

**Comment by codetheweb** [comment]
Please let me know if you figure out how to reproduce it, otherwise there's not much I can do. :)

**Comment by azukaar** [comment]
Happened again today, just in the middle of a song, nothing specific done to trigger it.
Looking at the log i have attached it sounds like you're not catching errors from the Spotify API rejecting an API call, causing the bot to crash

**Comment by codetheweb** [comment]
Ah, I think I might see the issue. I believe 2.1.1 should fix this.
