### ISSUE TITLE
i get this when starting the bot with node 16

### ISSUE THREAD

**Issue by samrudd** [codetheweb/muse#792]
muse@2.1.6 start
> npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts

> muse@2.1.6 env:set-database-url
> tsx src/scripts/run-with-database-url.ts tsx src/scripts/migrate-and-start.ts

/home/container/node_modules/.prisma/client/index.js:3
    throw new Error(
          ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at PrismaClient (/home/container/node_modules/.prisma/client/index.js:3:11)
    at <anonymous> (/home/container/src/utils/db.ts:3:23)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
Error: Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts
    at makeError (/home/container/node_modules/execa/lib/null:59:11)
    at handlePromise (/home/container/node_modules/execa/null:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at <anonymous> (/home/container/src/scripts/run-with-database-url.ts:6:3) {
  shortMessage: 'Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts',
  command: 'tsx src/scripts/migrate-and-start.ts',
  escapedCommand: 'tsx "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by samrudd** [comment]
I had to manually initialise the prisma and then it worked perfectly
