### ISSUE TITLE
Could not find settings for guild

### ISSUE THREAD

**Issue by TwoBrake** [codetheweb/muse#841]
I am trying to setup Muse in my server on my Ubuntu VPS and I get the error "🚫ope: Could not find settings for guild". I have double checked my ".env" file and all of the settings seem to be correct. Does anyone have any idea on how to fix this?

**Comment by Dragondarn1993** [comment]
You need to invite your bot again after you start the bot.

**Comment by TwoBrake** [comment]
It worked, but I got this error.

      throw new Error(`type ${type} is not known`);
            ^

Error: type adSlotRenderer is not known
    at parseItem (/var/hnlMusic/node_modules/ytsr/lib/parseItem.js:81:13)
    at catchAndLogFunc (/var/hnlMusic/node_modules/ytsr/lib/parseItem.js:88:12)
    at module.exports (/var/hnlMusic/node_modules/ytsr/lib/parseItem.js:111:46)
    at <anonymous> (/var/hnlMusic/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/var/hnlMusic/node_modules/ytsr/lib/main.js:53:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KeyValueCacheProvider.wrap (/var/hnlMusic/src/services/key-value-cache.ts:53:20)
    at async run (file:///var/hnlMusic/node_modules/p-queue/dist/index.js:115:36)

**Comment by TwoBrake** [comment]
Now it doesn't error, but when the bot plays a song, it says it is playing but then nothing happens.

**Comment by TwoBrake** [comment]
Okay, so I tried reinstalling the bot entirely, following all of the steps and I got this error:

Invalid prisma.keyValueCache.delete() invocation in
/var/hnlMusic/src/services/key-value-cache.ts:44:34

  41   return JSON.parse(cachedResult.value) as F;
  42 }
  43 
→ 44 await prisma.keyValueCache.delete(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 1032 }, Some("attempt to write a readonly database"))) })

**Comment by codetheweb** [comment]
Sounds like you might need to make sure the folder containing Muse / the database is writable by the user running Muse:

https://matthewsetter.com/sqlite-attempt-to-write-to-readonly-database/

**Comment by whytf** [comment]
Is there a particular reason that the bot needs to be reinvited for first time?

**Comment by codetheweb** [comment]
> Is there a particular reason that the bot needs to be reinvited for first time?

This is not needed in general, but sometimes helps if the server configuration changes or you recently upgraded Muse from a very old version.

If you need help with something specific, please open a new issue.

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
