### ISSUE TITLE
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')

### ISSUE THREAD

**Issue by Jack1424** [codetheweb/muse#913]
**What's happening?**
When I try to play a song (using the /play command), the bot says that it added something to the queue, but does not join the voice channel and shows an error in the console.

**Logs**
```
muse-muse-1  | /usr/app/node_modules/ytsr/lib/parseItem.js:355
muse-muse-1  |     .reelPlayerOverlayRenderer.reelPlayerHeaderSupportedRenderers.reelPlayerHeaderRenderer;
muse-muse-1  |                                                                   ^
muse-muse-1  | 
muse-muse-1  | TypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
muse-muse-1  |     at parseShort (/usr/app/node_modules/ytsr/lib/parseItem.js:355:67)
muse-muse-1  |     at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:28:14)
muse-muse-1  |     at <anonymous> (/usr/app/node_modules/ytsr/lib/parseItem.js:409:30)
muse-muse-1  |     at Array.map (<anonymous>)
muse-muse-1  |     at parseShelf (/usr/app/node_modules/ytsr/lib/parseItem.js:409:21)
muse-muse-1  |     at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:32:14)
muse-muse-1  |     at catchAndLogFunc (/usr/app/node_modules/ytsr/lib/parseItem.js:88:12)
muse-muse-1  |     at module.exports (/usr/app/node_modules/ytsr/lib/parseItem.js:111:46)
muse-muse-1  |     at <anonymous> (/usr/app/node_modules/ytsr/lib/main.js:53:34)
muse-muse-1  |     at Array.map (<anonymous>)
muse-muse-1  | 
muse-muse-1  | /********************************************************************************************************************************************************************************************************
muse-muse-1  | failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
muse-muse-1  | pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
muse-muse-1  | os: linux-x64, node.js: v18.7.0, ytsr: 3.8.0
muse-muse-1  | ********************************************************************************************************************************************************************************************************\
```

**Additional context**
This problem occurs when run both standalone and through Docker

**Runtime**
I'm running Muse:
- [X] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: v2.2.1 and codetheweb/muse:latest
- Docker (if applicable): 23.0.1
- OS: Ubuntu Server 22.04.2
- Node.js: 16.19.1
- ffmpeg: 4.4.2

**Comment by Jack1424** [comment]
It seems like this is a known issue with ystr. There are multiple issues and a few PRs on https://github.com/TimeForANinja/node-ytsr to resolve this but no changes have been made yet.
