### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by MobilGame06** [codetheweb/muse#928]
**What's happening?**
This error appeared randomly and the bot crashed
**Logs**
```
2023-03-31T20:59:18.608216493Z Error: Cannot perform IP discovery - socket closed

2023-03-31T20:59:18.608291483Z     at Socket.<anonymous> (/usr/app/node_modules/@discordjs/voice/src/networking/VoiceUDPSocket.ts:202:43)

2023-03-31T20:59:18.608354951Z     at Object.onceWrapper (node:events:627:28)

2023-03-31T20:59:18.608364213Z     at Socket.emit (node:events:525:35)

2023-03-31T20:59:18.608373366Z     at socketCloseNT (node:dgram:746:8)

2023-03-31T20:59:18.608390759Z     at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

2023-03-31T20:59:18.608399792Z Emitted 'error' event on VoiceConnection instance at:

2023-03-31T20:59:18.608418780Z     at VoiceConnection2.onNetworkingError (/usr/app/node_modules/@discordjs/voice/src/VoiceConnection.ts:496:8)

2023-03-31T20:59:18.608427690Z     at Networking.emit (node:events:513:28)

2023-03-31T20:59:18.608436310Z     at <anonymous> (/usr/app/node_modules/@discordjs/voice/src/networking/Networking.ts:422:35)

2023-03-31T20:59:18.608463908Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-03-31T20:59:18.608518839Z 

2023-03-31T20:59:18.608536662Z Node.js v18.7.0

2023-03-31T20:59:18.702010648Z Error: Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts

2023-03-31T20:59:18.702114090Z     at makeError (/usr/app/node_modules/execa/lib/null:59:11)

2023-03-31T20:59:18.702124201Z     at handlePromise (/usr/app/node_modules/execa/null:119:26)
```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.2.2
- Docker (if applicable): 20.10.12, build 20.10.12-0ubuntu2~18.04.1
- OS: ubuntu 18.04
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by ahatdude** [comment]
Bot is also crashing for me, here are the logs:
`03/26/2023 8:42:45 AM
Node.js v18.7.0
03/26/2023 8:42:55 AM
Error: Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts
03/26/2023 8:42:55 AM
    at makeError (/usr/app/node_modules/execa/lib/null:59:11)
03/26/2023 8:42:55 AM
    at handlePromise (/usr/app/node_modules/execa/null:119:26)
03/26/2023 8:42:55 AM
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
03/26/2023 8:42:55 AM
    at <anonymous> (/usr/app/src/scripts/run-with-database-url.ts:6:3) {
03/26/2023 8:42:55 AM
  shortMessage: 'Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts',
03/26/2023 8:42:55 AM
  command: 'tsx src/scripts/migrate-and-start.ts',
03/26/2023 8:42:55 AM
  escapedCommand: 'tsx "src/scripts/migrate-and-start.ts"',
03/26/2023 8:42:55 AM
  exitCode: 1,
03/26/2023 8:42:55 AM
  signal: undefined,
03/26/2023 8:42:55 AM
  signalDescription: undefined,
03/26/2023 8:42:55 AM
  stdout: undefined,
03/26/2023 8:42:55 AM
  stderr: undefined,
03/26/2023 8:42:55 AM
  failed: true,
03/26/2023 8:42:55 AM
  timedOut: false,
03/26/2023 8:42:55 AM
  isCanceled: false,
03/26/2023 8:42:55 AM
  killed: false
03/26/2023 8:42:55 AM
}
03/26/2023 8:42:55 AM
03/26/2023 8:42:55 AM
Node.js v18.7.0
03/26/2023 8:42:55 AM
error Command failed with exit code 1.`

**Comment by codetheweb** [comment]
Sounds like you might have a firewall issue?

https://github.com/discordjs/discord.js/issues/8728

**Comment by ahatdude** [comment]
> Sounds like you might have a firewall issue?
> 
> [discordjs/discord.js#8728](https://github.com/discordjs/discord.js/issues/8728)

So do you think I should open udp ports between 45000 and 60000 on my router?

I currently have it running on docker in unRAID.

Thanks!

**Comment by MobilGame06** [comment]
> Sounds like you might have a firewall issue?
> 
> [discordjs/discord.js#8728](https://github.com/discordjs/discord.js/issues/8728)

i don't have a firewall which could prevent that

**Comment by codetheweb** [comment]
> So do you think I should open udp ports between 45000 and 60000 on my router?

You don't need to port forward if that's what you're asking.

@MobilGame06 are you able to try running outside of Docker to see if there's some weird Docker networking config issue?

**Comment by MobilGame06** [comment]
> > So do you think I should open udp ports between 45000 and 60000 on my router?
> 
> You don't need to port forward if that's what you're asking.
> 
> @MobilGame06 are you able to try running outside of Docker to see if there's some weird Docker networking config issue?

didn't help same error

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
