### ISSUE TITLE
Issues with using bot.

### ISSUE THREAD

**Issue by Xalvas** [codetheweb/muse#933]
After updating the bot to the latest version, each play command creates the following logs:

`yarn run v1.22.19
$ npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts
> muse@2.2.3 env:set-database-url
> tsx src/scripts/run-with-database-url.ts
========================================
========================================
================= muse =================
========================================
=========== Made with 🎶 by ============
==== https://github.com/codetheweb =====
========================================
========================================
Running version 2.2.3 built on 4/5/2023 (commit 640ec2b13f3d19e64800b102a8295effc485c709)
🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb
- Applying database migrations...
✔ Database migrations applied.
- 📡 connecting to Discord...
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=267699976329625602&scope=bot%20applications.commands&permissions=36700160
/usr/app/node_modules/ytsr/lib/parseItem.js:357
    .reelPlayerOverlayRenderer.reelPlayerHeaderSupportedRenderers.reelPlayerHeaderRenderer;
                                                                  ^
TypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
    at parseShort (/usr/app/node_modules/ytsr/lib/parseItem.js:357:67)
    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:28:14)
    at <anonymous> (/usr/app/node_modules/ytsr/lib/parseItem.js:411:30)
    at Array.map (<anonymous>)
    at parseShelf (/usr/app/node_modules/ytsr/lib/parseItem.js:411:21)
    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/usr/app/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/usr/app/node_modules/ytsr/lib/parseItem.js:113:46)
    at <anonymous> (/usr/app/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-arm64, node.js: v18.7.0, ytsr: 3.8.1
********************************************************************************************************************************************************************************************************\
/usr/app/node_modules/ytsr/lib/parseItem.js:357
    .reelPlayerOverlayRenderer.reelPlayerHeaderSupportedRenderers.reelPlayerHeaderRenderer;
                                                                  ^
TypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
    at parseShort (/usr/app/node_modules/ytsr/lib/parseItem.js:357:67)
    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:28:14)
    at <anonymous> (/usr/app/node_modules/ytsr/lib/parseItem.js:411:30)
    at Array.map (<anonymous>)
    at parseShelf (/usr/app/node_modules/ytsr/lib/parseItem.js:411:21)
    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/usr/app/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/usr/app/node_modules/ytsr/lib/parseItem.js:113:46)
    at <anonymous> (/usr/app/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-arm64, node.js: v18.7.0, ytsr: 3.8.1
********************************************************************************************************************************************************************************************************\
Error checking for updates: Status code: 403
You can disable this check by setting the `YTDL_NO_UPDATE` env variable.
`

**Comment by melloirl** [comment]
I believe this is the exact same problem described in issue #932. 
Seems to be an issue with ytdl-core and we'll have to wait for a fix.

@redr00t provided a temporary workaround which seems to be working fine:
https://hub.docker.com/r/redr00t/muse

**Comment by codetheweb** [comment]
To clarify @Xalvas, does `/play` work and you're just seeing those errors/warnings or is nothing working?

The error in your logs should have been fixed in https://github.com/codetheweb/muse/pull/931.

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
