### ISSUE TITLE
No spotify songs can be played, 🚫 ope: no songs found

### ISSUE THREAD

**Issue by RainOrigami** [codetheweb/muse#958]
**What's happening?**

Since a couple of weeks ago, the bot started to refuse to play any spotify songs or playlists. Single youtube songs work.
The reply is always "🚫 ope: no songs found" with an error in console. I've received these console errors before and they have never been a problem, I don't know if they are related. Just to be safe I've also attached one of the files from the drumps dir.

I've completely removed the folder and re-cloned the repo, regenerated the api keys, nothing has helped.

Command used:
`/play https://open.spotify.com/playlist/17JJ2oOKjsfxa5G82Ikk3m?si=92844e60378e4e7d`

**Logs**

```
Aug 11 18:31:07 host bash[1996563]: /********************************************************************************************************************************************************************************************************
Aug 11 18:31:07 host bash[1996563]: failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
Aug 11 18:31:07 host bash[1996563]: pls post the the files in /home/rain/src/muse/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
Aug 11 18:31:07 host bash[1996563]: os: linux-x64, node.js: v16.20.0, ytsr: 3.8.2
Aug 11 18:31:07 host bash[1996563]: ********************************************************************************************************************************************************************************************************\
Aug 11 18:31:08 host bash[1996563]: /home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:431
Aug 11 18:31:08 host bash[1996563]:   const ownerUrl = owner.navigationEndpoint.browseEndpoint.canonicalBaseUrl ||
Aug 11 18:31:08 host bash[1996563]:                                             ^
Aug 11 18:31:08 host bash[1996563]: TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
Aug 11 18:31:08 host bash[1996563]:     at _parseOwner (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:431:45)
Aug 11 18:31:08 host bash[1996563]:     at parseMovie (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:346:12)
Aug 11 18:31:08 host bash[1996563]:     at parseItem (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:26:14)
Aug 11 18:31:08 host bash[1996563]:     at catchAndLogFunc (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:90:12)
Aug 11 18:31:08 host bash[1996563]:     at module.exports (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:113:46)
Aug 11 18:31:08 host bash[1996563]:     at <anonymous> (/home/rain/src/muse/node_modules/ytsr/lib/main.js:53:34)
Aug 11 18:31:08 host bash[1996563]:     at Array.map (<anonymous>)
Aug 11 18:31:08 host bash[1996563]:     at module.exports (/home/rain/src/muse/node_modules/ytsr/lib/main.js:53:25)
Aug 11 18:31:08 host bash[1996563]:     at runMicrotasks (<anonymous>)
Aug 11 18:31:08 host bash[1996563]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 11 18:31:08 host bash[1996563]: /********************************************************************************************************************************************************************************************************
Aug 11 18:31:08 host bash[1996563]: failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
Aug 11 18:31:08 host bash[1996563]: pls post the the files in /home/rain/src/muse/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
Aug 11 18:31:08 host bash[1996563]: os: linux-x64, node.js: v16.20.0, ytsr: 3.8.2
Aug 11 18:31:08 host bash[1996563]: ********************************************************************************************************************************************************************************************************\
Aug 11 18:31:13 host bash[1996563]: /home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:431
Aug 11 18:31:13 host bash[1996563]:   const ownerUrl = owner.navigationEndpoint.browseEndpoint.canonicalBaseUrl ||
Aug 11 18:31:13 host bash[1996563]:                                             ^
Aug 11 18:31:13 host bash[1996563]: TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
Aug 11 18:31:13 host bash[1996563]:     at _parseOwner (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:431:45)
Aug 11 18:31:13 host bash[1996563]:     at parseMovie (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:346:12)
Aug 11 18:31:13 host bash[1996563]:     at parseItem (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:26:14)
Aug 11 18:31:13 host bash[1996563]:     at catchAndLogFunc (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:90:12)
Aug 11 18:31:13 host bash[1996563]:     at module.exports (/home/rain/src/muse/node_modules/ytsr/lib/parseItem.js:113:46)
Aug 11 18:31:13 host bash[1996563]:     at <anonymous> (/home/rain/src/muse/node_modules/ytsr/lib/main.js:53:34)
Aug 11 18:31:13 host bash[1996563]:     at Array.map (<anonymous>)
Aug 11 18:31:13 host bash[1996563]:     at module.exports (/home/rain/src/muse/node_modules/ytsr/lib/main.js:53:25)
Aug 11 18:31:13 host bash[1996563]:     at runMicrotasks (<anonymous>)
Aug 11 18:31:13 host bash[1996563]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 11 18:31:13 host bash[1996563]: /********************************************************************************************************************************************************************************************************
Aug 11 18:31:13 host bash[1996563]: failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
Aug 11 18:31:13 host bash[1996563]: pls post the the files in /home/rain/src/muse/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
Aug 11 18:31:13 host bash[1996563]: os: linux-x64, node.js: v16.20.0, ytsr: 3.8.2
Aug 11 18:31:13 host bash[1996563]: ********************************************************************************************************************************************************************************************************\
```

**Additional context**

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository

**Versions**
- Muse: 2.4.1
- OS: Linux 5.15.0-72-generic Ubuntu 22.04.2 LTS
- Node.js: v16.20.0
- ffmpeg: 4.4.2-0ubuntu0.22.04.1

**Comment by MathiasDevelopes** [comment]
Having the same error.

**Comment by codetheweb** [comment]
I think this is related to https://github.com/codetheweb/muse/issues/948.

Please upgrade and see if it's fixed.

**Comment by RainOrigami** [comment]
Tested with Muse 2.4.2 and I am still getting 
![image](https://github.com/codetheweb/muse/assets/51454971/70f6e2c4-746d-4eda-8bdc-f5a893b74e2f)
And
```
Sep 01 15:33:12 myhost bash[3635696]: ✔ Ready! Invite the bot with https://discordapp.com/oauth2/...
Sep 01 15:33:45 myhost bash[3635696]: /home/myuser/src/muse/node_modules/ytsr/lib/parseItem.js:431
Sep 01 15:33:45 myhost bash[3635696]:   const ownerUrl = owner.navigationEndpoint.browseEndpoint.canonicalBaseUrl ||
Sep 01 15:33:45 myhost bash[3635696]:                                             ^
Sep 01 15:33:45 myhost bash[3635696]: TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
Sep 01 15:33:45 myhost bash[3635696]:     at _parseOwner (/home/myuser/src/muse/node_modules/ytsr/lib/parseItem.js:431:45)
Sep 01 15:33:45 myhost bash[3635696]:     at parseMovie (/home/myuser/src/muse/node_modules/ytsr/lib/parseItem.js:346:12)
Sep 01 15:33:45 myhost bash[3635696]:     at parseItem (/home/myuser/src/muse/node_modules/ytsr/lib/parseItem.js:26:14)
Sep 01 15:33:45 myhost bash[3635696]:     at catchAndLogFunc (/home/myuser/src/muse/node_modules/ytsr/lib/parseItem.js:90:12)
Sep 01 15:33:45 myhost bash[3635696]:     at module.exports (/home/myuser/src/muse/node_modules/ytsr/lib/parseItem.js:113:46)
Sep 01 15:33:45 myhost bash[3635696]:     at <anonymous> (/home/myuser/src/muse/node_modules/ytsr/lib/main.js:53:34)
Sep 01 15:33:45 myhost bash[3635696]:     at Array.map (<anonymous>)
Sep 01 15:33:45 myhost bash[3635696]:     at module.exports (/home/myuser/src/muse/node_modules/ytsr/lib/main.js:53:25)
Sep 01 15:33:45 myhost bash[3635696]:     at runMicrotasks (<anonymous>)
Sep 01 15:33:45 myhost bash[3635696]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Sep 01 15:33:45 myhost bash[3635696]: /********************************************************************************************************************************************************************************************************
Sep 01 15:33:45 myhost bash[3635696]: failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
Sep 01 15:33:45 myhost bash[3635696]: pls post the the files in /home/myuser/src/muse/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
Sep 01 15:33:45 myhost bash[3635696]: os: linux-x64, node.js: v16.20.0, ytsr: 3.8.2
Sep 01 15:33:45 myhost bash[3635696]: ********************************************************************************************************************************************************************************************************\
```

Tested with Spotify playlist https://open.spotify.com/playlist/17JJ2oOKjsfxa5G82Ikk3m?si=4cfcd0344c914a56

**Comment by mateus0099** [comment]
+1 ;'(

**Comment by ahatdude** [comment]
Still having this problem too.

**Comment by JoshStevensMC** [comment]
yea seems to be hit or miss

**Comment by GitGurky** [comment]
Same issue here on debian with muse version 2.4.3

**Comment by DeadlyVirez** [comment]
Yep also still having the same issue with 2.4.3

**Comment by Revq** [comment]
Ubuntu 22.04 LTS with 2.4.3 issue persists

**Comment by SkipTam** [comment]
I have the same issue

**Comment by narendnp** [comment]
I also have the same issue. Ubuntu 22.04 running version 2.4.4. 

Slightly unrelated but youtube playback also doesn't work (same issue with #988).

**Comment by teheim** [comment]
anyone managed to get this fixed? having the same issue right now

**Comment by GitGurky** [comment]
> anyone managed to get this fixed? having the same issue right now

I installed the docker version and it went away

**Comment by RainOrigami** [comment]
> I installed the docker version and it went away

can not confirm, used the `docker run` command from the README.md and tried to play [my playlist](https://open.spotify.com/playlist/17JJ2oOKjsfxa5G82Ikk3m?si=5f38902107134631) and still got the error "🚫 ope: no songs found" with the following log:

```
/usr/app/node_modules/ytsr/lib/parseItem.js:431
  const ownerUrl = owner.navigationEndpoint.browseEndpoint.canonicalBaseUrl ||
                                            ^

TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner (/usr/app/node_modules/ytsr/lib/parseItem.js:431:45)
    at parseMovie (/usr/app/node_modules/ytsr/lib/parseItem.js:346:12)
    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:26:14)
    at catchAndLogFunc (/usr/app/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/usr/app/node_modules/ytsr/lib/parseItem.js:113:46)
    at <anonymous> (/usr/app/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/usr/app/node_modules/ytsr/lib/main.js:53:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at KeyValueCacheProvider.wrap (/usr/app/src/services/key-value-cache.ts:53:20)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v18.7.0, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************\
/usr/app/node_modules/ytsr/lib/parseItem.js:431
  const ownerUrl = owner.navigationEndpoint.browseEndpoint.canonicalBaseUrl ||
                                            ^

TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner (/usr/app/node_modules/ytsr/lib/parseItem.js:431:45)
    at parseMovie (/usr/app/node_modules/ytsr/lib/parseItem.js:346:12)
    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:26:14)
    at catchAndLogFunc (/usr/app/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/usr/app/node_modules/ytsr/lib/parseItem.js:113:46)
    at <anonymous> (/usr/app/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/usr/app/node_modules/ytsr/lib/main.js:53:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at KeyValueCacheProvider.wrap (/usr/app/src/services/key-value-cache.ts:53:20)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v18.7.0, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************
```

**Comment by filip2cz** [comment]
same issue here

**Comment by codetheweb** [comment]
does this still happen on the latest version? we bumped a few dependencies

**Comment by ryleu** [comment]
I had this issue until I also added a YouTube API key. As soon as I added that and restarted the bot it worked fine.

**Comment by Palette300** [comment]
> does this still happen on the latest version? we bumped a few dependencies

yes, i also have this problem. 
if anyone knows how to fix it please let me know

**Comment by Adair-GA** [comment]
> yes, i also have this problem. if anyone knows how to fix it please let me know

add Warp like this to your `docker-compose.yml`:

```yaml
version: '3.4'

services:
  muse:
    image: ghcr.io/museofficial/muse
    restart: always
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN={TOKEN}
      - YOUTUBE_API_KEY={TOKEN}
      - SPOTIFY_CLIENT_ID={TOKEN}
      - SPOTIFY_CLIENT_SECRET={TOKEN}
    tty: true
    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp

 ```

**Comment by jcpt928** [comment]
I am having this exact issue - all TOKENs configured. No logs seem to be showing up in the "Logs" console. Am I missing something here?

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
