### ISSUE TITLE
bot doesnt accept my discord bot token and wont start

### ISSUE THREAD

**Issue by back-lacking** [codetheweb/muse#963]
**What's happening?**
The bot doesnt accept my token and therefore it doesnt start. read the token guide on the readme. token was obtained through the discord dev portal,. ive reset bot token multiple times
**Logs**
``` bash
- 📡 connecting to Discord...
/usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136
    const invalidToken = new DiscordjsError(ErrorCodes.TokenInvalid);
                         ^
Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/usr/app/node_modules/discord.js/src/client/Client.js:226:21)
    at bot_default.register (/usr/app/src/bot.ts:166:23)
    at startBot (/usr/app/src/index.ts:21:13)
    at <anonymous> (/usr/app/src/scripts/migrate-and-start.ts:82:3) {
  code: 'TokenInvalid'
}
Node.js v18.7.0
Error: Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts
    at makeError (/usr/app/node_modules/execa/lib/null:59:11)
    at handlePromise (/usr/app/node_modules/execa/null:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/usr/app/src/scripts/run-with-database-url.ts:6:3) {
  shortMessage: 'Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts',
  command: 'tsx src/scripts/migrate-and-start.ts',
  escapedCommand: 'tsx "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Node.js v18.7.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Runtime**
I'm running Muse:
through docker using docker compose

**Versions**
- Muse: 2.4.2
- Docker (if applicable): 20.10.24+dfsg1, build 297e128
- Docker Compose: v2.20.2
- OS: Debian 12

**Comment by codetheweb** [comment]
Are you absolutely sure it's a bot token?

You should have obtained it from a section that looks like this:

![Screenshot 2023-08-17 at 7 29 44 PM](https://github.com/codetheweb/muse/assets/7410405/4f6c7562-50e1-473b-9d99-c5ebdcf11826)

If so, please open an issue on Discord.js--there's nothing I can do here.

**Comment by back-lacking** [comment]
@codetheweb yes i got it from there. I will pass this onto discord.js

**Comment by Zakhiel2** [comment]
I'm currently getting the same error using Docker.
@back-lacking Did you find a way?
