### ISSUE TITLE
Bot Fails to Start

### ISSUE THREAD

**Issue by CheeseburgerOps** [codetheweb/muse#996]
**What's happening?**
The container fails to start

**Logs**

```
/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:47
  return new WebapiError(response.body, response.headers, response.statusCode, response.body);
         ^

WebapiError: [object Object]
    at _toError (/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:47:10)
    at <anonymous> (/usr/app/node_modules/spotify-web-api-node/src/http-manager.js:71:25)
    at callback (/usr/app/node_modules/superagent/src/node/index.js:902:3)
    at IncomingMessage.<anonymous> (/usr/app/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  body: {},
  headers: {
    'content-type': 'text/html; charset=UTF-8',
    'referrer-policy': 'no-referrer',
    'content-length': '304',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close'
  },
  statusCode: 403,
  attemptNumber: 6,
  retriesLeft: 0
}

Node.js v18.7.0
Error: Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts
    at makeError (/usr/app/node_modules/execa/lib/null:59:11)
    at handlePromise (/usr/app/node_modules/execa/null:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/usr/app/src/scripts/run-with-database-url.ts:6:3) {
  shortMessage: 'Command failed with exit code 1: tsx src/scripts/migrate-and-start.ts',
  command: 'tsx src/scripts/migrate-and-start.ts',
  escapedCommand: 'tsx "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}


```

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest
- Docker (if applicable): 23.0.1
- OS: Oracle Linux 8
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by codetheweb** [comment]
Based on that output you're not using the latest version of Muse, can you please update and try again?

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
