### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by kohbo** [codetheweb/muse#998]
**What's happening?**
Every command ends in a "The application did not respond" error on Discord

**Logs**

```
redbot-muse-1  | 2024-02-12T17:07:35.055Z muse DiscordAPIError[10062]: Unknown interaction
redbot-muse-1  |     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
redbot-muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
redbot-muse-1  |     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
redbot-muse-1  |     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
redbot-muse-1  |     at async ChatInputCommandInteraction.reply (/usr/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
redbot-muse-1  |     at default_1.execute (/usr/app/src/commands/config.ts:117:9)
redbot-muse-1  |     at Client.<anonymous> (/usr/app/src/bot.ts:79:13)
redbot-muse-1  | 2024-02-12T17:08:14.790Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 50ms.
redbot-muse-1  | 2024-02-12T17:08:56.073Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 49ms.
redbot-muse-1  | 2024-02-12T17:09:37.365Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 50ms.
redbot-muse-1  | 2024-02-12T17:10:18.617Z muse [WS => Shard 0] Heartbeat acknowledged, latency of 49ms.
redbot-muse-1  | 2024-02-12T17:10:23.415Z prisma:client  Prisma Client call:
redbot-muse-1  | 2024-02-12T17:10:23.415Z prisma:client  prisma.keyValueCache.findUnique({
redbot-muse-1  |   where: {
redbot-muse-1  |     key: 'autocomplete:b'
redbot-muse-1  |   }
redbot-muse-1  | })
redbot-muse-1  | 2024-02-12T17:10:23.415Z prisma:client  Generated request:
redbot-muse-1  | 2024-02-12T17:10:23.415Z prisma:client  query {
redbot-muse-1  |   findUniqueKeyValueCache(where: {
redbot-muse-1  |     key: "autocomplete:b"
redbot-muse-1  |   }) {
redbot-muse-1  |     key
redbot-muse-1  |     value
redbot-muse-1  |     expiresAt
redbot-muse-1  |     createdAt
redbot-muse-1  |     updatedAt
redbot-muse-1  |   }
redbot-muse-1  | }
redbot-muse-1  | 
redbot-muse-1  | 2024-02-12T17:10:23.416Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
redbot-muse-1  | 2024-02-12T17:10:23.416Z muse Cache hit: autocomplete:b
redbot-muse-1  | 2024-02-12T17:10:25.396Z prisma:client  Prisma Client call:
redbot-muse-1  | 2024-02-12T17:10:25.396Z prisma:client  prisma.setting.findUnique({
redbot-muse-1  |   where: {
redbot-muse-1  |     guildId: '742178676942176258'
redbot-muse-1  |   }
redbot-muse-1  | })
redbot-muse-1  | 2024-02-12T17:10:25.396Z prisma:client  Generated request:
redbot-muse-1  | 2024-02-12T17:10:25.396Z prisma:client  query {
redbot-muse-1  |   findUniqueSetting(where: {
redbot-muse-1  |     guildId: "742178676942176258"
redbot-muse-1  |   }) {
redbot-muse-1  |     guildId
redbot-muse-1  |     playlistLimit
redbot-muse-1  |     secondsToWaitAfterQueueEmpties
redbot-muse-1  |     leaveIfNoListeners
redbot-muse-1  |     createdAt
redbot-muse-1  |     updatedAt
redbot-muse-1  |   }
redbot-muse-1  | }
redbot-muse-1  | 
redbot-muse-1  | 2024-02-12T17:10:25.397Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
redbot-muse-1  | 2024-02-12T17:10:25.663Z prisma:client  Prisma Client call:
redbot-muse-1  | 2024-02-12T17:10:25.663Z prisma:client  prisma.keyValueCache.findUnique({
redbot-muse-1  |   where: {
redbot-muse-1  |     key: 'autocomplete:boom boom boom boom'
redbot-muse-1  |   }
redbot-muse-1  | })
redbot-muse-1  | 2024-02-12T17:10:25.663Z prisma:client  Generated request:
redbot-muse-1  | 2024-02-12T17:10:25.663Z prisma:client  query {
redbot-muse-1  |   findUniqueKeyValueCache(where: {
redbot-muse-1  |     key: "autocomplete:boom boom boom boom"
redbot-muse-1  |   }) {
redbot-muse-1  |     key
redbot-muse-1  |     value
redbot-muse-1  |     expiresAt
redbot-muse-1  |     createdAt
redbot-muse-1  |     updatedAt
redbot-muse-1  |   }
redbot-muse-1  | }
redbot-muse-1  | 
redbot-muse-1  | 2024-02-12T17:10:25.663Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
redbot-muse-1  | 2024-02-12T17:10:25.664Z muse Cache hit: autocomplete:boom boom boom boom
redbot-muse-1  | 2024-02-12T17:10:26.123Z muse DiscordAPIError[10062]: Unknown interaction
redbot-muse-1  |     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
redbot-muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
redbot-muse-1  |     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
redbot-muse-1  |     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
redbot-muse-1  |     at async AutocompleteInteraction.respond (/usr/app/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
redbot-muse-1  |     at default_1.handleAutocompleteInteraction (/usr/app/src/commands/play.ts:62:7)
redbot-muse-1  |     at Client.<anonymous> (/usr/app/src/bot.ts:99:13)
redbot-muse-1  | 2024-02-12T17:10:27.617Z muse DiscordAPIError[10062]: Unknown interaction
redbot-muse-1  |     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
redbot-muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
redbot-muse-1  |     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
redbot-muse-1  |     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
redbot-muse-1  |     at async AutocompleteInteraction.respond (/usr/app/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
redbot-muse-1  |     at default_1.handleAutocompleteInteraction (/usr/app/src/commands/play.ts:84:5)
redbot-muse-1  |     at Client.<anonymous> (/usr/app/src/bot.ts:99:13)
redbot-muse-1  | 2024-02-12T17:10:30.101Z muse DiscordAPIError[10062]: Unknown interaction
redbot-muse-1  |     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
redbot-muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
redbot-muse-1  |     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
redbot-muse-1  |     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
redbot-muse-1  |     at async ChatInputCommandInteraction.deferReply (/usr/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
redbot-muse-1  |     at AddQueryToQueue.addToQueue (/usr/app/src/services/add-query-to-queue.ts:42:5)
redbot-muse-1  |     at default_1.execute (/usr/app/src/commands/play.ts:49:5)
redbot-muse-1  |     at Client.<anonymous> (/usr/app/src/bot.ts:79:13)
redbot-muse-1  | 2024-02-12T17:10:31.542Z muse DiscordAPIError[50035]: Invalid Form Body
redbot-muse-1  | data.choices[6].name[BASE_TYPE_BAD_LENGTH]: Must be between 1 and 100 in length.
redbot-muse-1  |     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
redbot-muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
redbot-muse-1  |     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
redbot-muse-1  |     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
redbot-muse-1  |     at async AutocompleteInteraction.respond (/usr/app/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
redbot-muse-1  |     at default_1.handleAutocompleteInteraction (/usr/app/src/commands/play.ts:84:5)
redbot-muse-1  |     at Client.<anonymous> (/usr/app/src/bot.ts:99:13)

```

**Screenshots**
![image](https://github.com/codetheweb/muse/assets/6541769/5cdf9051-c21f-4ae1-9a55-ee4916c75a6c)

**Additional context**
Compose File
```
version: '3.4'

services:
  muse:
    image: codetheweb/muse:latest
    restart: always
    volumes:
      - ./data:/data
    environment:
      - DISCORD_TOKEN=<redacted>
      - YOUTUBE_API_KEY=<redacted>
      - SPOTIFY_CLIENT_ID=<redacted>
      - SPOTIFY_CLIENT_SECRET=<redacted>
      - DEBUG=*
      - 
```

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [ x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.5.0 built on 1/17/2024 (commit 03d960d31a21235d2adec3feac662ef863657a7a)
- Docker (if applicable): Docker version 20.10.24, build 297e128
- OS: Unraid
- Node.js: NA (using Docker)
- ffmpeg: NA (using Docker)

**Comment by kohbo** [comment]
Occasionally the `/play` command works, but all others end in the same error.

[logs.txt](https://github.com/codetheweb/muse/files/14241643/logs.txt)

**Comment by kohbo** [comment]
Might be a related issue: https://github.com/discordjs/discord.js/issues/7005

**Comment by codetheweb** [comment]
Looks like deferring command responses might work if you're on a slower network. Happy to accept a PR to make this an option/enabled by default.

**Comment by kohbo** [comment]
I'll give it a shot.

To be clear, though, I'm not on a slow network; neither referring to latency or bandwidth (1Gb symmetrical). None of the hardware resources are anywhere near capacity either. If this clears it up, it may be a sign that something else in my system isn't functioning properly. 

Anyway, thanks for taking a look at the issue.

**Comment by sportsziggy** [comment]
@kohbo did yours ever clear up? Mine does it like every other request

**Comment by erwanclx** [comment]
Same issue here

**Comment by gknoop** [comment]
> Same issue here

Yeah, this has been a recurring issue for me for a while. This should likely be merged with #1004 and #1010.

**Comment by BarkerB** [comment]
Same issue here unfortunately

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
